const $=function(id){return document.getElementById(id)};
const state={cases:[],recipients:[],activeCase:''};
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
function csv(value){return String(value||'').split(/[\n,]/).map(function(item){return item.trim()}).filter(Boolean)}
function fmt(value){return value?new Date(value).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'-'}
function toast(message){var el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){el.classList.remove('show')},3500)}
async function req(path,options){options=options||{};var response=await fetch(path,Object.assign({cache:'no-store',credentials:'same-origin'},options,{headers:Object.assign({'Content-Type':'application/json'},options.headers||{})}));var data={};try{data=await response.json()}catch(e){}if(!response.ok){var error=new Error(data.error||'요청 실패 ('+response.status+')');error.status=response.status;throw error}return data}

function showView(name){$('dashboardView').hidden=name!=='dashboard';$('adminView').hidden=name!=='admin';document.querySelectorAll('.nav').forEach(function(button){button.classList.toggle('active',button.dataset.view===name)});if(name==='admin')loadAdmin();else loadDashboard(state.activeCase)}
document.querySelectorAll('.nav').forEach(function(button){button.onclick=function(){showView(button.dataset.view)}});

function renderCaseStrip(cases){
  $('activeCaseCount').textContent=cases.length+'개 케이스 가동';
  var items=['<button class="case-chip '+(state.activeCase?'':'active')+'" data-case=""><b>전체 모니터링</b><small>모든 케이스 통합</small></button>'];
  cases.forEach(function(item){items.push('<button class="case-chip '+(state.activeCase===item.id?'active':'')+'" data-case="'+item.id+'"><b>'+esc(item.name)+'</b><small>'+(item.delivery_mode==='immediate'?'즉시 발송':esc((item.delivery_times||[]).join(', ')||'예약'))+' · 기준 '+item.relevance_threshold+'%</small></button>')});
  $('caseStrip').innerHTML=items.join('');
  $('caseStrip').querySelectorAll('[data-case]').forEach(function(button){button.onclick=function(){state.activeCase=button.dataset.case;loadDashboard(state.activeCase)}});
  $('caseFilter').innerHTML='<option value="">전체 케이스</option>'+cases.map(function(item){return '<option value="'+item.id+'">'+esc(item.name)+'</option>'}).join('');
  $('caseFilter').value=state.activeCase;
}
function renderArticles(items){
  if(!items.length){$('articleList').innerHTML='<div class="empty">아직 분석된 기사가 없습니다.</div>';return}
  $('articleList').innerHTML=items.map(function(item){
    var categories=(item.low_score_categories||[]).slice(0,2).map(function(value){return '<span>'+esc(value)+'</span>'}).join('');
    return '<article class="article"><div class="score" style="--score:'+Number(item.final_score||0)+'"><b>'+Math.round(item.final_score||0)+'%</b></div><div><div class="article-meta"><span class="badge '+(item.decision==='low'?'low':'')+'">'+esc(item.case_name)+'</span><span>'+esc(item.publisher||'언론사 미확인')+'</span><span>'+fmt(item.published_at||item.first_seen_at)+'</span></div><h3><a href="'+esc(item.original_url)+'" target="_blank" rel="noopener noreferrer">'+esc(item.title)+'</a></h3><p>'+esc(item.summary||'요약 대기')+'</p><div class="score-parts"><span>키워드 '+Math.round(item.keyword_score||0)+'</span><span>의미 '+Math.round(item.semantic_score||0)+'</span><span>LLM '+Math.round(item.llm_score||0)+'</span>'+categories+'</div></div></article>'
  }).join('');
}
function renderBars(items){var max=Math.max.apply(null,[1].concat(items.map(function(item){return Number(item.value||0)})));$('publisherBars').innerHTML=items.length?items.map(function(item){return '<div class="bar-row"><label title="'+esc(item.label)+'">'+esc(item.label||'미확인')+'</label><div class="bar-track"><i style="width:'+(Number(item.value||0)/max*100)+'%"></i></div><b>'+item.value+'</b></div>'}).join(''):'<div class="empty">집계 대기</div>'}
function renderDeliveries(items){var labels={pending:'대기',retry:'재시도',sent:'성공',failed:'실패'};$('deliveryStats').innerHTML=items.length?items.map(function(item){return '<div><b>'+item.value+'</b><span>'+(labels[item.status]||esc(item.status))+'</span></div>'}).join(''):'<div><b>0</b><span>발송 기록</span></div>'}
async function loadDashboard(caseId){caseId=caseId||'';try{var data=await req('/api/poc/master-press/dashboard'+(caseId?'?case_id='+encodeURIComponent(caseId):''));var stats=data.dashboard.stats||{};state.cases=data.cases||[];renderCaseStrip(state.cases);renderArticles(data.dashboard.articles||[]);renderBars(data.dashboard.publishers||[]);renderDeliveries(data.dashboard.deliveries||[]);$('metricTotal').textContent=Number(stats.total||0).toLocaleString();$('metricSend').textContent=Number(stats.sent_candidates||0).toLocaleString();$('metricAverage').textContent=Number(stats.average_score||0).toFixed(0)+'%';$('metricLow').textContent=Number(stats.low||0).toLocaleString();$('lastUpdated').textContent=new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})+' 갱신'}catch(error){toast(error.message)}}
$('caseFilter').onchange=function(event){state.activeCase=event.target.value;loadDashboard(state.activeCase)};

function readyLabel(key){return {naver_news:'네이버 뉴스',kakao_login:'카카오 로그인',token_encryption:'토큰 암호화',supabase:'Supabase',ollama:'Ollama'}[key]||key}
function renderAdmin(data){
  state.cases=data.cases||[];state.recipients=data.recipients||[];
  $('readiness').innerHTML=Object.entries(data.readiness||{}).map(function(pair){return '<span class="ready-pill '+(pair[1]?'':'off')+'">'+readyLabel(pair[0])+' · '+(pair[1]?'준비':'설정 필요')+'</span>'}).join('');
  $('caseCount').textContent=state.cases.length+'/5';
  $('caseList').innerHTML=state.cases.length?state.cases.map(function(item){var schedule=item.collection_mode==='interval'?item.collection_interval_minutes+'분':(item.collection_times||[]).join(', ');return '<div class="case-row"><button data-edit="'+item.id+'"><b>'+esc(item.name)+'</b><small>'+(item.is_active?'가동':'중지')+' · '+esc(schedule)+' · 기준 '+item.relevance_threshold+'%</small></button><div class="row-actions"><button data-run="'+item.id+'">지금 수집</button><button data-edit="'+item.id+'">설정</button></div></div>'}).join(''):'<div class="empty">새 케이스를 만들어주세요.</div>';
  $('recipientList').innerHTML=state.recipients.length?state.recipients.map(function(item){return '<div class="recipient-row"><div><b>'+esc(item.label)+'</b><small>'+esc(item.status)+' · 토큰 '+fmt(item.access_token_expires_at)+'까지</small></div><div class="row-actions"><button data-test="'+item.id+'">테스트</button><button data-remove-recipient="'+item.id+'">해제</button></div></div>'}).join(''):'<div class="empty">카카오 수신자 등록 링크를 생성하세요.</div>';
  $('improvementCase').innerHTML=state.cases.map(function(item){return '<option value="'+item.id+'">'+esc(item.name)+'</option>'}).join('')||'<option value="">케이스 없음</option>';
  bindRows();renderRecipientChecks([]);loadImprovement();
}
function bindRows(){
  document.querySelectorAll('[data-edit]').forEach(function(button){button.onclick=function(){openCase(state.cases.find(function(item){return item.id===button.dataset.edit}))}});
  document.querySelectorAll('[data-run]').forEach(function(button){button.onclick=async function(){button.disabled=true;try{var result=await req('/api/poc/master-press/admin/cases/'+button.dataset.run+'/run',{method:'POST',body:'{}'});toast('수집 완료 · 신규 '+(result.counts&&result.counts.new||0)+' · 분석 '+(result.counts&&result.counts.scored||0));await loadAdmin()}catch(error){toast(error.message)}finally{button.disabled=false}}});
  document.querySelectorAll('[data-test]').forEach(function(button){button.onclick=async function(){button.disabled=true;try{await req('/api/poc/master-press/admin/recipients/'+button.dataset.test+'/test',{method:'POST',body:'{}'});toast('테스트 메시지를 발송했습니다.')}catch(error){toast(error.message)}finally{button.disabled=false}}});
  document.querySelectorAll('[data-remove-recipient]').forEach(function(button){button.onclick=async function(){if(!confirm('수신자 연결과 토큰을 삭제할까요?'))return;try{await req('/api/poc/master-press/admin/recipients/'+button.dataset.removeRecipient,{method:'DELETE'});toast('수신자 연결을 해제했습니다.');loadAdmin()}catch(error){toast(error.message)}}});
}
async function loadAdmin(){try{await req('/api/admin/session');$('adminGate').hidden=true;$('adminContent').hidden=false;renderAdmin(await req('/api/poc/master-press/admin/bootstrap'))}catch(error){if(error.status===401){$('adminGate').hidden=false;$('adminContent').hidden=true}else toast(error.message)}}

function renderRecipientChecks(selected){$('caseRecipients').innerHTML=state.recipients.length?state.recipients.map(function(item){return '<label><input type="checkbox" value="'+item.id+'" '+(selected.indexOf(item.id)>=0?'checked':'')+'>'+esc(item.label)+'</label>'}).join(''):'<span>등록된 수신자가 없습니다.</span>'}
function openCase(item){
  item=item||null;$('caseDialogTitle').textContent=item?'케이스 수정':'새 케이스';$('caseId').value=item&&item.id||'';$('caseName').value=item&&item.name||'';$('caseActive').value=String(item?item.is_active:true);$('caseTopic').value=item&&item.topic_description||'';$('caseInclude').value=(item&&item.include_terms||[]).join(', ');$('caseRequired').value=(item&&item.required_terms||[]).join(', ');$('caseExclude').value=(item&&item.exclude_terms||[]).join(', ');$('caseUrgent').value=(item&&item.urgent_terms||[]).join(', ');$('collectionMode').value=item&&item.collection_mode||'interval';$('collectionInterval').value=String(item&&item.collection_interval_minutes||30);$('collectionTimes').value=(item&&item.collection_times||[]).join(', ');$('deliveryMode').value=item&&item.delivery_mode||'immediate';$('deliveryTimes').value=(item&&item.delivery_times||[]).join(', ');$('relevanceThreshold').value=item&&item.relevance_threshold!=null?item.relevance_threshold:75;$('holdThreshold').value=item&&item.hold_threshold!=null?item.hold_threshold:55;$('keywordWeight').value=item&&item.keyword_weight!=null?item.keyword_weight:.3;$('semanticWeight').value=item&&item.semantic_weight!=null?item.semantic_weight:.4;$('llmWeight').value=item&&item.llm_weight!=null?item.llm_weight:.3;$('rssUrls').value=(item&&item.rss_urls||[]).join('\n');renderRecipientChecks(item&&item.recipient_ids||[]);$('deleteCase').hidden=!item;$('caseDialog').showModal()
}
function casePayload(){return {name:$('caseName').value.trim(),is_active:$('caseActive').value==='true',topic_description:$('caseTopic').value.trim(),include_terms:csv($('caseInclude').value),required_terms:csv($('caseRequired').value),exclude_terms:csv($('caseExclude').value),urgent_terms:csv($('caseUrgent').value),synonym_terms:{},include_publishers:[],exclude_publishers:[],rss_urls:csv($('rssUrls').value),collection_mode:$('collectionMode').value,collection_interval_minutes:Number($('collectionInterval').value),collection_times:csv($('collectionTimes').value),delivery_mode:$('deliveryMode').value,delivery_times:csv($('deliveryTimes').value),relevance_threshold:Number($('relevanceThreshold').value),hold_threshold:Number($('holdThreshold').value),keyword_weight:Number($('keywordWeight').value),semantic_weight:Number($('semanticWeight').value),llm_weight:Number($('llmWeight').value),max_articles_per_message:2,recipient_ids:Array.from($('caseRecipients').querySelectorAll('input:checked')).map(function(input){return input.value})}}
$('newCase').onclick=function(){if(state.cases.length>=5)return toast('케이스는 최대 5개입니다.');openCase()};
$('caseForm').onsubmit=async function(event){event.preventDefault();var id=$('caseId').value;try{await req('/api/poc/master-press/admin/cases'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(casePayload())});$('caseDialog').close();toast('케이스 설정을 저장했습니다.');loadAdmin();loadDashboard()}catch(error){toast(error.message)}};
$('deleteCase').onclick=async function(){var id=$('caseId').value;if(!id||!confirm('케이스와 분석 기록을 삭제할까요?'))return;try{await req('/api/poc/master-press/admin/cases/'+id,{method:'DELETE'});$('caseDialog').close();toast('케이스를 삭제했습니다.');loadAdmin();loadDashboard()}catch(error){toast(error.message)}};
document.querySelectorAll('[data-close]').forEach(function(button){button.onclick=function(){$(button.dataset.close).close()}});

$('newInvite').onclick=function(){$('inviteResult').innerHTML='';$('inviteLabel').value='';$('inviteDialog').showModal()};
$('inviteForm').onsubmit=async function(event){event.preventDefault();try{var data=await req('/api/poc/master-press/admin/invites',{method:'POST',body:JSON.stringify({label:$('inviteLabel').value,ttl_minutes:Number($('inviteTtl').value)})});var url=data.invite.url;$('inviteResult').innerHTML='<b>수신자에게 아래 링크를 전달하세요.</b><p>'+esc(url)+'</p><button type="button" class="small-button" id="copyInvite">링크 복사</button>';$('copyInvite').onclick=async function(){await navigator.clipboard.writeText(url);toast('등록 링크를 복사했습니다.')}}catch(error){toast(error.message)}};
$('runTick').onclick=async function(){var button=$('runTick');button.disabled=true;try{var data=await req('/api/poc/master-press/admin/tick',{method:'POST',body:'{}'});toast('작업 완료 · 케이스 '+(data.cases&&data.cases.length||0)+' · 발송 '+(data.delivery&&data.delivery.sent||0));loadAdmin();loadDashboard()}catch(error){toast(error.message)}finally{button.disabled=false}};

async function loadImprovement(){var id=$('improvementCase').value;if(!id){$('improvementContent').innerHTML='<div class="empty">케이스를 먼저 만드세요.</div>';return}try{var data=await req('/api/poc/master-press/admin/cases/'+id+'/improvements?days=7');var categories=Object.entries(data.categories||{}).sort(function(a,b){return b[1]-a[1]});$('improvementContent').innerHTML='<div class="improvement-score"><span>7일 저점 표본</span><b>'+(data.sample_count||0)+'</b><small>평균 '+Number(data.average_score||0).toFixed(1)+'%</small></div><div><h3>주요 원인</h3><div class="score-parts">'+(categories.map(function(pair){return '<span>'+esc(pair[0])+' '+pair[1]+'</span>'}).join('')||'<span>분석 대기</span>')+'</div><h3>설정 개선 제안</h3><ul>'+((data.suggestions||[]).map(function(item){return '<li>'+esc(item)+'</li>'}).join('')||'<li>데이터가 쌓이면 사례별 제안을 표시합니다.</li>')+'</ul></div>'}catch(error){toast(error.message)}}
$('improvementCase').onchange=loadImprovement;
if(new URLSearchParams(location.search).get('admin')==='1')showView('admin');else loadDashboard();
if(new URLSearchParams(location.search).get('connected')==='1')toast('카카오 수신자 등록이 완료되었습니다.');
