const $=function(id){return document.getElementById(id)};
const state={cases:[],organizations:[],recipients:[],activeOrganization:'',activeCase:'',activeTags:[],topicTagsExpanded:false,llmModels:[],caseLlmModels:[],analysis:null,dashboardLoading:false,lastArticleId:'',refreshSeconds:60,refreshRemaining:60,refreshTimer:null,countdownTimer:null,isAdmin:false,neuralOrganization:'',neuralCase:'',neuralDays:7,neuralScene:null,neuralSelected:'',neuralRotation:{x:-.18,y:.35,zoom:1},pressOrganization:''};
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
function csv(value){return String(value||'').split(/[\n,]/).map(function(item){return item.trim()}).filter(Boolean)}
function fmt(value){return value?new Date(value).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'-'}
function evidenceLabel(value){var labels={verified:'근거 확인',target_unverified:'대상 근거 미확인',stance_unverified:'어조 근거 미확인',target_and_stance_unverified:'대상·어조 근거 미확인',body_limited_verified:'본문 제한 · 근거 확인',body_limited_target_unverified:'본문 제한 · 대상 근거 미확인',body_limited_stance_unverified:'본문 제한 · 어조 근거 미확인',body_limited_target_and_stance_unverified:'본문 제한 · 대상·어조 근거 미확인'};return labels[value]||''}
function toast(message){var dialog=$('analysisDialog');var el=dialog&&dialog.open?$('analysisToast'):$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){el.classList.remove('show')},3500)}
async function req(path,options){options=options||{};var response=await fetch(path,Object.assign({cache:'no-store',credentials:'same-origin'},options,{headers:Object.assign({'Content-Type':'application/json'},options.headers||{})}));var data={};try{data=await response.json()}catch(e){}if(!response.ok){var error=new Error(data.error||'요청 실패 ('+response.status+')');error.status=response.status;throw error}return data}

function showView(name,focusId){$('dashboardView').hidden=name!=='dashboard';$('neuralView').hidden=name!=='neural';$('pressView').hidden=name!=='press';$('adminView').hidden=name!=='admin';document.querySelectorAll('.nav').forEach(function(button){button.classList.toggle('active',button.dataset.view===name)});if(name==='admin')loadAdmin();else if(name==='neural')loadNeural();else if(name==='press')loadPress(focusId);else loadDashboard(state.activeCase,state.activeOrganization)}
document.querySelectorAll('.nav').forEach(function(button){button.onclick=function(){showView(button.dataset.view)}});

function renderFilters(organizations,cases){
  state.organizations=organizations||[];state.cases=cases||[];
  if(state.activeOrganization&&!state.organizations.some(function(item){return item.id===state.activeOrganization}))state.activeOrganization='';
  if(!state.activeOrganization&&state.organizations.length===1)state.activeOrganization=state.organizations[0].id;
  var scopedCases=state.activeOrganization?state.cases.filter(function(item){return item.organization_id===state.activeOrganization}):[];
  if(state.activeCase&&!scopedCases.some(function(item){return item.id===state.activeCase}))state.activeCase='';
  $('activeCaseCount').textContent=state.organizations.length+'개 기관 · '+state.cases.length+'개 케이스 가동';
  $('organizationFilter').innerHTML='<option value="">전체 기관</option>'+state.organizations.map(function(item){return '<option value="'+item.id+'">'+esc(item.name)+'</option>'}).join('');
  $('organizationFilter').value=state.activeOrganization;
  $('caseFilter').innerHTML='<option value="">전체 케이스</option>'+scopedCases.map(function(item){return '<option value="'+item.id+'">'+esc(item.name)+'</option>'}).join('');
  $('caseFilter').value=state.activeCase;$('caseFilter').disabled=!state.activeOrganization;
  var organization=state.organizations.find(function(item){return item.id===state.activeOrganization});
  var currentCase=state.cases.find(function(item){return item.id===state.activeCase});
  $('activeFilterLabel').textContent=currentCase?((organization?organization.name+' / ':'')+currentCase.name):(organization?organization.name+' / 전체 케이스':'전체 기관');
  renderNeuralOptions();renderPressOrganizationOptions();
}
$('organizationFilter').onchange=function(event){state.activeOrganization=event.target.value;state.activeCase='';loadDashboard('',state.activeOrganization)};
$('caseFilter').onchange=function(event){state.activeCase=event.target.value;loadDashboard(state.activeCase,state.activeOrganization)};

function articleStatusLabel(item){var labels={pending:'공통 분석 대기',processing:'공통 분석 중',completed:'공통 분석 완료',failed:'공통 분석 실패'};return labels[item.status]||item.status||'수집됨'}
function caseStatusLabel(item){var delivery=item.deliveries||{};if(item.evaluation_status==='excluded')return '후보 제외';if(item.evaluation_status==='pending')return '유사도 판정 대기';if(item.evaluation_status==='processing')return '유사도 판정 중';if(item.evaluation_status==='failed')return '판정 실패';if(item.decision==='send'){if(delivery.sent)return '발송 완료';if(delivery.pending||delivery.retry)return '발송 예정';return '조건 충족'}return item.decision==='low'?'발송 제외':'판정 대기'}
function renderArticles(items){
  if(!items.length){$('articleList').innerHTML='<div class="empty">아직 수집·분석된 기사가 없습니다.</div>';return}
  $('articleList').innerHTML=items.map(function(item){
    var cases=item.case_results||[],summary=item.case_summary||{},topScore=cases.reduce(function(max,value){return Math.max(max,Number(value.similarity_score!=null?value.similarity_score:(value.llm_score||0)))},0);
    var org=cases[0]&&cases[0].organization_name||'기관 미확인';
    var tags=[org,item.tone].concat(item.classification_tags||[]).filter(Boolean).filter(function(value,index,list){return list.indexOf(value)===index});
    var classificationTags=tags.slice(0,5).map(function(value,index){return '<span class="'+(index===0?'organization-tag':'')+'">#'+esc(value)+'</span>'}).join('');
    var progress='케이스 '+Number(summary.total||0)+'개 · 충족 '+Number(summary.matched||0)+' · 제외 '+Number(summary.excluded||0)+' · 대기 '+Number(summary.pending||0);
    var details=cases.length?'<details class="case-status-details"><summary>'+esc(progress)+'</summary><div class="case-status-list">'+cases.map(function(value){var delivery=value.deliveries||{};var score=value.evaluation_status==='completed'?'유사도 '+Math.round(value.similarity_score!=null?value.similarity_score:(value.llm_score||0))+'% · ':'';var send=delivery.sent?' · 발송 '+delivery.sent+'건':delivery.pending?' · 발송 예정 '+delivery.pending+'건':'';return '<div><b>'+esc(value.case_name||'케이스')+'</b><span class="case-state '+esc(value.decision||value.evaluation_status)+'">'+esc(caseStatusLabel(value))+'</span><small>'+score+esc(send||'')+'</small></div>'}).join('')+'</div></details>':'<div class="case-progress">'+esc(item.status==='completed'?'케이스 후보 분배 대기':'공통 분석 완료 후 케이스별로 판정합니다.')+'</div>';
    var commonStatus='<span class="badge '+(item.status==='completed'?'':'low')+'">'+esc(articleStatusLabel(item))+'</span>';
    return '<article class="article article-group"><div class="article-score-column"><div class="score" style="--score:'+topScore+'"><b>'+(topScore?Math.round(topScore)+'%':'-')+'</b></div><button class="related-press-button" type="button" data-article-press="'+esc(item.id)+'">관련 보도자료 ('+Number(item.related_press_count||0)+')</button></div><div><div class="score-parts article-tags">'+classificationTags+'</div><div class="article-meta">'+commonStatus+'<span>'+esc(item.publisher||'언론사 미확인')+'</span><span>'+fmt(item.published_at||item.first_seen_at)+'</span></div><h3><a href="'+esc(item.original_url)+'" target="_blank" rel="noopener noreferrer">'+esc(item.title)+'</a></h3><p>'+esc(item.summary||'공통 요약 대기')+'</p><div class="score-parts"><span>'+esc(item.article_type||'분류 대기')+'</span><span>어조 '+esc(item.tone||'사실전달')+'</span><span>'+esc(progress)+'</span></div>'+details+'</div></article>'
  }).join('');
  $('articleList').querySelectorAll('[data-article-press]').forEach(function(button){button.onclick=function(){openArticlePress(button.dataset.articlePress)}});
}
function renderTagFilter(items){
  var root=$('tagFilter');if(!root)return;
  var toneOrder=['사실전달','부정적','긍정적'];
  var topics=items.filter(function(item){return toneOrder.indexOf(item.label)<0}).sort(function(a,b){var aa=state.activeTags.indexOf(a.label)>=0,bb=state.activeTags.indexOf(b.label)>=0;return aa===bb?Number(b.value||0)-Number(a.value||0):(aa?-1:1)});
  var tones=toneOrder.map(function(label){return items.find(function(item){return item.label===label})||{label:label,value:0}});
  function chips(values){return values.map(function(item){var active=state.activeTags.indexOf(item.label)>=0;return '<button class="tag-chip '+(active?'active':'')+'" data-tag="'+esc(item.label)+'">#'+esc(item.label)+' ('+Number(item.value||0)+')</button>'}).join('')}
  root.innerHTML='<div class="tag-filter-row"><b>주제</b><div id="topicTagList" class="tag-filter-list '+(state.topicTagsExpanded?'expanded':'')+'">'+(chips(topics)||'<small>분류 대기</small>')+'</div><button id="topicTagExpand" class="tag-expand" type="button" hidden>'+(state.topicTagsExpanded?'접기':'펼치기')+'</button></div><div class="tag-filter-row tone-filter-row"><b>어조</b><div class="tag-filter-list">'+chips(tones)+'</div></div>';
  root.querySelectorAll('[data-tag]').forEach(function(button){button.onclick=function(){var tag=button.dataset.tag;var index=state.activeTags.indexOf(tag);if(index>=0)state.activeTags.splice(index,1);else state.activeTags.push(tag);loadDashboard(state.activeCase,state.activeOrganization)}})
  requestAnimationFrame(function(){var list=$('topicTagList'),toggle=$('topicTagExpand');if(!list||!toggle)return;var overflow=list.scrollHeight>list.clientHeight+2;if(overflow||state.topicTagsExpanded)toggle.hidden=false;toggle.onclick=function(){state.topicTagsExpanded=!state.topicTagsExpanded;list.classList.toggle('expanded',state.topicTagsExpanded);toggle.textContent=state.topicTagsExpanded?'접기':'펼치기'}})
}
function renderBars(items){var max=Math.max.apply(null,[1].concat(items.map(function(item){return Number(item.value||0)})));$('publisherBars').innerHTML=items.length?items.map(function(item){return '<div class="bar-row"><label title="'+esc(item.label)+'">'+esc(item.label||'미확인')+'</label><div class="bar-track"><i style="width:'+(Number(item.value||0)/max*100)+'%"></i></div><b>'+item.value+'</b></div>'}).join(''):'<div class="empty compact">집계 대기</div>'}
function renderCategories(items){$('categoryStats').innerHTML=items.length?items.map(function(item){return '<div><span>'+esc(item.label||'기타')+'</span><b>'+Number(item.article_count||0).toLocaleString()+' <small>('+Number(item.sent_count||0).toLocaleString()+')</small></b></div>'}).join(''):'<div class="empty compact">분류 대기</div>'}
function renderDeliveries(items){var labels={pending:'대기',retry:'재시도',sent:'성공',failed:'실패'};$('deliveryStats').innerHTML=items.length?items.map(function(item){return '<div><b>'+item.value+'</b><span>'+(labels[item.status]||esc(item.status))+'</span></div>'}).join(''):'<div><b>0</b><span>발송 기록</span></div>'}
function renderRecentSent(items){$('recentSent').innerHTML=items.length?items.map(function(item){return '<article><a href="'+esc(item.original_url)+'" target="_blank" rel="noopener noreferrer">'+esc(item.title)+'</a><small>'+esc(item.organization_name||item.organization_tag||'기관 미확인')+' / '+esc(item.case_name)+' · '+fmt(item.sent_at)+'</small></article>'}).join(''):'<div class="empty compact">최근 발송 기사가 없습니다.</div>'}
function renderDashboardSnapshot(data){
  var dashboard=data.dashboard||{},stats=dashboard.stats||{},articles=dashboard.articles||[];
  renderFilters(data.organizations||[],data.cases||[]);
  renderArticles(articles);renderTagFilter(dashboard.tags||[]);renderBars(dashboard.publishers||[]);renderCategories(dashboard.categories||[]);
  renderDeliveries(dashboard.deliveries||[]);renderRecentSent(dashboard.recent_sent||[]);renderPipelineStats(dashboard.pipeline||dashboard.llm||{},dashboard.deliveries||[]);
  $('metricTotal').textContent=Number(stats.total||0).toLocaleString();$('metricSend').textContent=Number(stats.sent_candidates||0).toLocaleString();$('metricAverage').textContent=Number(stats.average_score||0).toFixed(0)+'%';$('metricLow').textContent=Number(stats.low||0).toLocaleString();
  var latest=articles[0]&&articles[0].id||'';if(state.lastArticleId&&latest&&state.lastArticleId!==latest)toast('새 분석 기사가 기사 목록과 통계에 반영되었습니다.');state.lastArticleId=latest;
  $('lastUpdated').textContent=new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})+' · KST 00:00 기준 기사·통계 갱신';if(state.refreshSeconds){state.refreshRemaining=state.refreshSeconds;renderRefreshCountdown()}
}
function renderNeuralOptions(){var orgEl=$('neuralOrganizationFilter'),caseEl=$('neuralCaseFilter');if(!orgEl||!caseEl)return;if(state.neuralOrganization&&!state.organizations.some(function(item){return item.id===state.neuralOrganization}))state.neuralOrganization='';if(!state.neuralOrganization&&state.organizations.length)state.neuralOrganization=state.organizations[0].id;var scoped=state.cases.filter(function(item){return item.organization_id===state.neuralOrganization});if(!state.neuralCase||!scoped.some(function(item){return item.id===state.neuralCase}))state.neuralCase=scoped[0]&&scoped[0].id||'';orgEl.innerHTML='<option value="">기관 선택</option>'+state.organizations.map(function(item){return '<option value="'+item.id+'">'+esc(item.name)+'</option>'}).join('');orgEl.value=state.neuralOrganization;caseEl.innerHTML='<option value="">케이스 선택</option>'+scoped.map(function(item){return '<option value="'+item.id+'">'+esc(item.name)+'</option>'}).join('');caseEl.value=state.neuralCase;caseEl.disabled=!state.neuralOrganization}
function neuralHash(value){var hash=0;for(var i=0;i<String(value).length;i++)hash=(hash*31+String(value).charCodeAt(i))>>>0;return hash/4294967295}
function renderNeuralWords(words){var root=$('neuralWordCloud');if(!root)return;if(!words.length){root.innerHTML='<div class="empty compact">선택한 케이스에 표시할 화두가 없습니다.</div>';return}var max=Math.max.apply(null,words.map(function(item){return Number(item.value||0)}));root.innerHTML=words.slice(0,28).map(function(item,index){var ratio=Number(item.value||0)/max,angle=index*2.3999632297,radius=index?20+Math.sqrt(index)*26*(1-ratio*.45):0;var x=50+Math.cos(angle)*radius/3.9,y=50+Math.sin(angle)*radius/2.5,size=12+Math.round(ratio*25);return '<span style="left:'+x+'%;top:'+y+'%;font-size:'+size+'px;z-index:'+Math.round(ratio*10)+'">'+esc(item.label)+'</span>'}).join('')}
function neuralColor(tone){return tone==='부정적'?'#ff8179':tone==='긍정적'?'#56d7a2':'#72bde9'}
function buildNeuralLayout(scene){
  var nodes=scene.nodes||[],edges=scene.edges||[],adjacency={};nodes.forEach(function(node){adjacency[node.id]=[]});edges.forEach(function(edge){if(adjacency[edge.source]&&adjacency[edge.target]){adjacency[edge.source].push(edge.target);adjacency[edge.target].push(edge.source)}});
  var visited={},components=[];nodes.forEach(function(node){if(visited[node.id])return;var stack=[node.id],ids=[];visited[node.id]=true;while(stack.length){var id=stack.pop();ids.push(id);(adjacency[id]||[]).forEach(function(next){if(!visited[next]){visited[next]=true;stack.push(next)}})}components.push(ids)});components.sort(function(a,b){return b.length-a.length||String(a[0]).localeCompare(String(b[0]))});
  var grouped=components.filter(function(ids){return ids.length>1}),isolated=components.filter(function(ids){return ids.length===1}),positions={};
  function spherePoint(index,total,radius){var y=1-2*(index+.5)/Math.max(1,total),ring=Math.sqrt(Math.max(0,1-y*y)),angle=index*2.3999632297;return{x:Math.cos(angle)*ring*radius,y:y*radius*.72,z:Math.sin(angle)*ring*radius}}
  grouped.forEach(function(ids,groupIndex){var center=grouped.length===1?{x:0,y:0,z:0}:spherePoint(groupIndex,grouped.length,210),localRadius=38+Math.sqrt(ids.length)*17;ids.forEach(function(id,index){var local=spherePoint(index,ids.length,localRadius),seed=neuralHash(id+'depth');positions[id]={x:center.x+local.x,y:center.y+local.y,z:center.z+local.z+(seed-.5)*20}})});
  isolated.forEach(function(ids,index){var outer=spherePoint(index,isolated.length,grouped.length?345:285),seed=neuralHash(ids[0]);positions[ids[0]]={x:outer.x+(seed-.5)*35,y:outer.y+(neuralHash(ids[0]+'y')-.5)*35,z:outer.z+(neuralHash(ids[0]+'z')-.5)*35}});
  scene.layout=positions;scene.componentCount=components.length;scene.groupCount=grouped.length;scene.isolatedCount=isolated.length;
}
function initNeuralCanvas(){var canvas=$('neuralCanvas');if(!canvas||canvas.dataset.ready)return;canvas.dataset.ready='1';var drag=null;canvas.addEventListener('pointerdown',function(event){drag={x:event.clientX,y:event.clientY,moved:false};canvas.setPointerCapture(event.pointerId)});canvas.addEventListener('pointermove',function(event){if(!drag)return;var dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>3)drag.moved=true;state.neuralRotation.y+=dx*.009;state.neuralRotation.x=Math.max(-1.35,Math.min(1.35,state.neuralRotation.x+dy*.009));drag.x=event.clientX;drag.y=event.clientY;drawNeural()});canvas.addEventListener('pointerup',function(event){if(drag&&!drag.moved)selectNeuralNode(event);drag=null});canvas.addEventListener('wheel',function(event){event.preventDefault();state.neuralRotation.zoom=Math.max(.62,Math.min(2.1,state.neuralRotation.zoom*(event.deltaY>0?.92:1.08)));drawNeural()},{passive:false})}
function projectNeural(point,w,h){var ry=state.neuralRotation.y,rx=state.neuralRotation.x,x=point.x*Math.cos(ry)-point.z*Math.sin(ry),z=point.x*Math.sin(ry)+point.z*Math.cos(ry),y=point.y*Math.cos(rx)-z*Math.sin(rx);z=point.y*Math.sin(rx)+z*Math.cos(rx);var scale=state.neuralRotation.zoom*520/Math.max(300,780+z),depth=Math.max(.08,Math.min(1,(390-z)/780));return{x:w/2+x*scale,y:h/2+y*scale,z:z,scale:scale,depth:depth}}
function drawNeural(){
  var canvas=$('neuralCanvas'),scene=state.neuralScene;if(!canvas||!scene)return;if(!scene.layout)buildNeuralLayout(scene);var rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1,w=Math.max(300,rect.width),h=Math.max(260,rect.height);canvas.width=w*ratio;canvas.height=h*ratio;var ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);
  var background=ctx.createRadialGradient(w*.48,h*.43,20,w*.5,h*.5,Math.max(w,h)*.72);background.addColorStop(0,'#173d34');background.addColorStop(.5,'#0c2721');background.addColorStop(1,'#061410');ctx.fillStyle=background;ctx.fillRect(0,0,w,h);
  ctx.save();ctx.translate(w/2,h*.56);ctx.strokeStyle='rgba(112,203,165,.09)';ctx.lineWidth=1;for(var ring=1;ring<=6;ring++){ctx.beginPath();ctx.ellipse(0,0,ring*w*.085,ring*h*.035,0,0,Math.PI*2);ctx.stroke()}for(var ray=0;ray<12;ray++){var angle=ray*Math.PI/6;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.cos(angle)*w*.56,Math.sin(angle)*h*.22);ctx.stroke()}ctx.restore();
  var nodes=scene.nodes||[],edges=scene.edges||[],degree={};edges.forEach(function(edge){degree[edge.source]=(degree[edge.source]||0)+1;degree[edge.target]=(degree[edge.target]||0)+1});var maxDegree=Math.max.apply(null,[1].concat(Object.keys(degree).map(function(id){return degree[id]}))),lookup={};nodes.forEach(function(node){var importance=Math.min(1,(Number(node.score||0)/100)*.45+(degree[node.id]||0)/maxDegree*.7),position=scene.layout[node.id]||{x:0,y:0,z:0};lookup[node.id]={node:node,point:projectNeural(position,w,h),importance:importance}});
  edges.slice().sort(function(a,b){var az=((lookup[a.source]||{point:{z:0}}).point.z+(lookup[a.target]||{point:{z:0}}).point.z)/2,bz=((lookup[b.source]||{point:{z:0}}).point.z+(lookup[b.target]||{point:{z:0}}).point.z)/2;return bz-az}).forEach(function(edge){var a=lookup[edge.source],b=lookup[edge.target];if(!a||!b)return;var depth=(a.point.depth+b.point.depth)/2,alpha=Math.min(.78,(.08+Number(edge.weight||0)*.95)*depth);ctx.strokeStyle='rgba(91,221,174,'+alpha+')';ctx.lineWidth=.6+Number(edge.weight||0)*3*depth;ctx.shadowColor='rgba(69,226,164,.45)';ctx.shadowBlur=8*depth;ctx.beginPath();ctx.moveTo(a.point.x,a.point.y);ctx.lineTo(b.point.x,b.point.y);ctx.stroke()});ctx.shadowBlur=0;
  var ordered=Object.keys(lookup).map(function(id){return lookup[id]}).sort(function(a,b){return b.point.z-a.point.z});ordered.forEach(function(item){var selected=item.node.id===state.neuralSelected,depth=item.point.depth,size=(4+item.importance*9+(selected?3:0))*(.48+depth*.88);ctx.save();ctx.globalAlpha=selected?1:.18+depth*.8;ctx.filter=depth<.3?'blur(.55px)':'none';ctx.shadowColor=neuralColor(item.node.tone);ctx.shadowBlur=selected?24:5+depth*13;if(selected){ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(item.point.x,item.point.y,size+6,0,Math.PI*2);ctx.stroke()}ctx.fillStyle=neuralColor(item.node.tone);ctx.beginPath();ctx.arc(item.point.x,item.point.y,size,0,Math.PI*2);ctx.fill();ctx.restore();item.radius=size;if(selected||(item.importance>.78&&depth>.48)){ctx.font=(selected?'700 ':'600 ')+Math.round((selected?13:10)*( .72+depth*.42))+'px Noto Sans KR';var label=item.node.label.slice(0,22),measure=ctx.measureText(label).width;ctx.fillStyle='rgba(5,18,14,'+(selected?.86:.62)+')';ctx.fillRect(item.point.x+size+3,item.point.y-16,measure+8,18);ctx.fillStyle='rgba(238,250,245,'+(selected?1:.55+depth*.4)+')';ctx.fillText(label,item.point.x+size+7,item.point.y-3)}});scene.projected=lookup;
  ctx.fillStyle='rgba(210,235,225,.58)';ctx.font='10px Noto Sans KR';ctx.fillText('가까운 노드: 크고 선명함  ·  먼 노드: 작고 흐림',16,h-16);
}
function selectNeuralNode(event){var canvas=$('neuralCanvas'),scene=state.neuralScene;if(!canvas||!scene||!scene.projected)return;var rect=canvas.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top,best=null;Object.keys(scene.projected).forEach(function(id){var item=scene.projected[id],distance=Math.hypot(item.point.x-x,item.point.y-y),hit=Math.max(13,(item.radius||5)+7);if(distance<hit&&(!best||distance<best.distance))best={id:id,distance:distance,item:item}});if(!best)return;state.neuralSelected=best.id;var links=(scene.edges||[]).filter(function(edge){return edge.source===best.id||edge.target===best.id}).sort(function(a,b){return b.weight-a.weight});var node=best.item.node,topics=(node.topics||[]).map(function(value){return '<span>#'+esc(value)+'</span>'}).join(''),concepts=(node.topic_concepts||[]).map(function(value){return '<span>'+esc(value)+'</span>'}).join('');$('neuralDetail').innerHTML='<h3>'+esc(node.label)+'</h3><p>'+esc(node.summary||'요약 정보 없음')+'</p><div class="score-parts"><span>'+esc(node.article_type||'기타')+'</span><span>'+esc(node.tone||'사실전달')+'</span><span>케이스 점수 '+Math.round(node.score||0)+'</span></div><p><b>상위 주제</b></p><div class="score-parts">'+(concepts||'<span>의미 벡터로 관계 분석</span>')+'</div><p><b>직접 주제 명사</b></p><div class="score-parts">'+(topics||'<span>추출된 주제 명사 없음</span>')+'</div><p><b>주제 연결 '+links.length+'개</b></p><ul>'+links.slice(0,8).map(function(edge){var other=edge.source===best.id?scene.nodeMap[edge.target]:scene.nodeMap[edge.source],shared=(edge.shared_concepts||edge.shared_topics||[]).join(', '),kind=edge.relation_level==='abstract_topic'?'상위':'직접';return '<li>'+esc(other&&other.label||'기사')+' · '+kind+' '+Math.round(edge.weight*100)+'%'+(shared?' · '+esc(shared):'')+'</li>'}).join('')+'</ul>';drawNeural()}
function renderNeural(data){state.neuralScene={nodes:data.nodes||[],edges:data.edges||[],nodeMap:{}};(data.nodes||[]).forEach(function(node){state.neuralScene.nodeMap[node.id]=node});if(state.neuralSelected&&!state.neuralScene.nodeMap[state.neuralSelected])state.neuralSelected='';buildNeuralLayout(state.neuralScene);$('neuralMeta').textContent=(data.sent_only?'발송 완료 ':'')+(data.article_count||0)+'건 · 상위 주제 '+(data.abstract_topic_count||0)+'개 · 의미벡터 '+(data.semantic_vector_count||0)+'건 · 군집 '+(state.neuralScene.groupCount||0)+'개 · 연결 '+(data.edges||[]).length+'개';renderNeuralWords(data.words||[]);if(!data.article_count)$('neuralDetail').innerHTML='<div class="empty compact">분석할 발송 완료 기사가 아직 없습니다.</div>';else if(!state.neuralSelected)$('neuralDetail').innerHTML='<div class="empty compact">노드를 선택하면 상위 주제와 직접 명사 관계를 확인할 수 있습니다.</div>';initNeuralCanvas();drawNeural()}
async function loadNeural(){renderNeuralOptions();if(!state.neuralCase){$('neuralMeta').textContent='분석할 케이스를 선택하세요.';return}try{var params=new URLSearchParams({case_id:state.neuralCase,days:String(state.neuralDays),sent_only:'1'});if(state.neuralOrganization)params.set('organization_id',state.neuralOrganization);renderNeural(await req('/api/poc/master-press/analysis/insights?'+params.toString()))}catch(error){$('neuralMeta').textContent=error.message}}
$('neuralOrganizationFilter').onchange=function(event){state.neuralOrganization=event.target.value;state.neuralCase='';renderNeuralOptions();loadNeural()};$('neuralCaseFilter').onchange=function(event){state.neuralCase=event.target.value;loadNeural()};$('neuralDays').onchange=function(event){state.neuralDays=Number(event.target.value||7);loadNeural()};window.addEventListener('resize',function(){if(!$('neuralView').hidden)drawNeural()});


function renderPressOrganizationOptions(){
  var el=$('pressOrganizationFilter');if(!el)return;
  if(!state.pressOrganization||!state.organizations.some(function(item){return item.id===state.pressOrganization}))state.pressOrganization=state.activeOrganization||state.organizations[0]&&state.organizations[0].id||'';
  el.innerHTML='<option value="">기관 선택</option>'+state.organizations.map(function(item){return '<option value="'+item.id+'">'+esc(item.name)+'</option>'}).join('');
  el.value=state.pressOrganization;
}
function pressToneCounts(item){return '<div class="press-tone-counts"><span>사실전달 <b>'+Number(item.factual_count||0).toLocaleString()+'</b></span><span class="negative">부정적 <b>'+Number(item.negative_count||0).toLocaleString()+'</b></span><span class="positive">긍정적 <b>'+Number(item.positive_count||0).toLocaleString()+'</b></span></div>'}
function renderPressReleases(items){
  var root=$('pressReleaseList');if(!root)return;
  if(!items.length){root.innerHTML='<div class="empty">수집된 보도자료가 없습니다. 관리자 동기화 또는 다음 자동 수집을 기다려주세요.</div>';return}
  root.innerHTML=items.map(function(item){return '<article class="press-release-item" id="press-'+esc(item.id)+'"><button class="press-release-summary" data-press-toggle="'+esc(item.id)+'"><div><small>'+esc(item.organization_name||'행정안전부')+' · '+esc(item.department||'담당부서 확인 중')+' · '+fmt(item.published_at)+'</small><h3>'+esc(item.title)+'</h3></div>'+pressToneCounts(item)+'<b class="press-related-total">관련 기사 '+Number(item.related_article_count||0).toLocaleString()+'</b><i>＋</i></button><div class="press-release-detail" data-press-detail="'+esc(item.id)+'" hidden></div></article>'}).join('');
  root.querySelectorAll('[data-press-toggle]').forEach(function(button){button.onclick=function(){togglePressRelease(button.dataset.pressToggle)}})
}
function pressArticleList(items){return items&&items.length?'<div class="press-related-articles"><h4>관련 기사 '+items.length+'건</h4>'+items.map(function(article){return '<article><div><span class="tone '+(article.tone==='부정적'?'negative':article.tone==='긍정적'?'positive':'')+'">'+esc(article.tone||'사실전달')+'</span><a href="'+esc(article.original_url)+'" target="_blank" rel="noopener noreferrer">'+esc(article.title)+'</a></div><b>'+Math.round(Number(article.similarity_score||0))+'%</b></article>'}).join('')+'</div>':'<div class="empty compact">연관 기준을 충족한 기사가 아직 없습니다.</div>'}
async function togglePressRelease(id,forceOpen){
  var detail=document.querySelector('[data-press-detail="'+id+'"]'),item=document.getElementById('press-'+id);if(!detail||!item)return;
  if(!detail.hidden&&!forceOpen){detail.hidden=true;item.classList.remove('expanded');return}
  item.classList.add('expanded');detail.hidden=false;
  if(!detail.dataset.loaded){detail.innerHTML='<div class="empty compact">보도자료 내용을 불러오는 중입니다.</div>';try{var data=await req('/api/poc/master-press/press-releases/'+encodeURIComponent(id)),release=data.item||{};detail.dataset.loaded='1';detail.innerHTML='<p class="press-summary-text">'+esc(release.summary||'요약 정보가 없습니다.')+'</p><dl class="press-contact"><dt>관련부서</dt><dd>'+esc(release.department||'-')+'</dd><dt>담당자</dt><dd>'+esc(release.contact_name||'-')+'</dd><dt>연락처</dt><dd>'+esc(release.contact_phone||'-')+'</dd></dl><div class="press-detail-actions"><a class="small-button" href="'+esc(release.canonical_url)+'" target="_blank" rel="noopener noreferrer">행안부 원문 ↗</a><button class="small-button" type="button" data-full-markdown>전체 보기</button></div>'+pressArticleList(release.related_articles||[]);var full=detail.querySelector('[data-full-markdown]');full.onclick=function(){$('pressMarkdownTitle').textContent=release.title||'보도자료 전체 보기';$('pressMarkdownContent').textContent=release.markdown||'';$('pressMarkdownDialog').showModal()}}catch(error){detail.innerHTML='<div class="empty compact">'+esc(error.message)+'</div>'}}
  if(forceOpen)setTimeout(function(){item.scrollIntoView({behavior:'smooth',block:'center'})},80)
}
async function loadPress(focusId){
  try{
    if(!state.organizations.length){var dashboard=await req('/api/poc/master-press/dashboard?_='+Date.now());renderFilters(dashboard.organizations||[],dashboard.cases||[])}
    if(!state.isAdmin){var adminCheck=await fetch('/api/admin/session',{cache:'no-store',credentials:'same-origin'});state.isAdmin=adminCheck.ok}
    renderPressOrganizationOptions();$('syncPressReleases').hidden=!state.isAdmin;
    var params=new URLSearchParams({limit:'80',_:String(Date.now())});if(state.pressOrganization)params.set('organization_id',state.pressOrganization);
    var data=await req('/api/poc/master-press/press-releases?'+params.toString()),status=data.status||{},releaseCounts=status.releases||{},jobs=status.match_jobs||{};
    renderPressReleases(data.items||[]);
    var ragLabel=!status.supabase_enabled?'Supabase 미설정':status.supabase_status==='ready'?'Supabase RAG 준비':status.supabase_status==='syncing'?'Supabase 자동 동기화 중 ('+Number(status.supabase_pending||0).toLocaleString()+')':'Supabase 스키마 적용 대기';
    $('pressStatus').textContent='보도자료 '+Object.values(releaseCounts).reduce(function(sum,value){return sum+Number(value||0)},0).toLocaleString()+'건 · 연관 '+Number(status.related||0).toLocaleString()+'건 · 매칭 대기 '+Number(jobs.pending||0).toLocaleString()+' · '+ragLabel+(status.last_sync_at?' · 최근 자동 수집 '+fmt(status.last_sync_at):'');
    if(focusId)togglePressRelease(focusId,true)
  }catch(error){$('pressStatus').textContent=error.message;$('pressReleaseList').innerHTML='<div class="empty">'+esc(error.message)+'</div>'}
}
async function openArticlePress(articleId){
  var dialog=$('relatedPressDialog'),root=$('relatedPressList');root.innerHTML='<div class="empty compact">관련 보도자료를 확인하고 있습니다.</div>';dialog.showModal();
  try{var data=await req('/api/poc/master-press/articles/'+encodeURIComponent(articleId)+'/press-releases'),items=data.items||[];root.innerHTML=items.length?items.map(function(item){return '<button class="related-press-row" data-related-press="'+esc(item.id)+'"><div><b>'+esc(item.title)+'</b><small>'+esc(item.department||'행정안전부')+' · '+fmt(item.published_at)+'</small></div><strong>'+Math.round(Number(item.similarity_score||0))+'%</strong></button>'}).join(''):'<div class="empty compact">연관 기준을 충족한 보도자료가 없습니다.</div>';root.querySelectorAll('[data-related-press]').forEach(function(button){button.onclick=function(){dialog.close();showView('press',button.dataset.relatedPress)}})}catch(error){root.innerHTML='<div class="empty compact">'+esc(error.message)+'</div>'}
}
$('pressOrganizationFilter').onchange=function(event){state.pressOrganization=event.target.value;loadPress()};
$('syncPressReleases').onclick=async function(){var button=this;button.disabled=true;try{var result=await req('/api/poc/master-press/admin/press-releases/sync',{method:'POST',body:'{}'});toast('지금 동기화 완료 · 신규 '+Number(result.new||0)+'건');loadPress()}catch(error){toast(error.message)}finally{button.disabled=false}};

function renderDashboardWords(words,scopeLabel){var root=$('dashboardWordCloud'),meta=$('dashboardWordMeta');if(!root)return;if(!state.activeCase&&!state.activeOrganization){if(meta)meta.textContent='기관 또는 케이스를 선택하세요.';root.innerHTML='<div class="empty compact">기관 또는 케이스별 핵심 화두를 표시합니다.</div>';return}var visibleWords=(words||[]).slice(0,10);if(!visibleWords.length){if(meta)meta.textContent=(scopeLabel||'최근 7일')+' · 분석 결과 없음';root.innerHTML='<div class="empty compact">표시할 화두가 아직 없습니다.</div>';return}var max=Math.max.apply(null,visibleWords.map(function(item){return Number(item.value||0)}));if(meta)meta.textContent=(scopeLabel||'최근 7일')+' · 핵심 화두 10개';root.innerHTML=visibleWords.map(function(item,index){var ratio=Number(item.value||0)/max,rankWeight=Math.pow(1-index/9,.62),angle=index*2.3999632297,radius=index?26+Math.sqrt(index)*36*(1-ratio*.14):0,x=Math.max(15,Math.min(85,50+Math.cos(angle)*radius/3.45)),y=Math.max(14,Math.min(86,50+Math.sin(angle)*radius/3.15)),size=Math.round(13+23*rankWeight*(.8+.2*ratio));return '<span class="topic-word rank-'+index+'" style="left:'+x+'%;top:'+y+'%;font-size:'+size+'px">'+esc(item.label)+'</span>'}).join('')}
async function loadDashboardWords(){var params=new URLSearchParams({days:'7',delivery_only:'1'}),scopeLabel='';if(state.activeCase){params.set('case_id',state.activeCase);if(state.activeOrganization)params.set('organization_id',state.activeOrganization);scopeLabel='발송 대상 · 케이스 · 최근 7일'}else if(state.activeOrganization){params.set('organization_id',state.activeOrganization);params.set('scope','organization');scopeLabel='발송 대상 · 기관 전체 · 최근 7일'}else{renderDashboardWords([]);return}var requestedCase=state.activeCase,requestedOrganization=state.activeOrganization;try{var data=await req('/api/poc/master-press/analysis/insights?'+params.toString());if(requestedCase===state.activeCase&&requestedOrganization===state.activeOrganization)renderDashboardWords(data.words||[],scopeLabel)}catch(error){var meta=$('dashboardWordMeta');if(meta)meta.textContent='화두 집계 실패'}}

async function loadDashboard(caseId,organizationId){
  if(state.dashboardLoading)return;
  state.dashboardLoading=true;state.activeCase=caseId||'';state.activeOrganization=organizationId||'';
  try{
    var adminSession=await fetch('/api/admin/session',{cache:'no-store',credentials:'same-origin'});state.isAdmin=adminSession.ok;
    var params=new URLSearchParams();if(state.activeOrganization)params.set('organization_id',state.activeOrganization);if(state.activeCase)params.set('case_id',state.activeCase);if(state.activeTags.length)params.set('tags',state.activeTags.join(','));params.set('_',String(Date.now()));
    renderDashboardSnapshot(await req('/api/poc/master-press/dashboard?'+params.toString()));
    loadDashboardWords();
  }catch(error){toast(error.message)}finally{state.dashboardLoading=false}
}

function renderPipelineStats(stats,deliveries){var common=stats.article_jobs||{},cases=stats.case_jobs||{},providers=stats.providers||{},commonProvider=providers.common||{},caseProvider=providers.case||{},delivery={};(deliveries||[]).forEach(function(item){delivery[item.status]=Number(item.value||0)});$('commonPending').textContent=Number(common.pending||0).toLocaleString();$('commonProcessing').textContent=Number(common.processing||0).toLocaleString();$('commonCompleted').textContent=Number(common.completed||0).toLocaleString();$('casePending').textContent=Number(cases.pending||0).toLocaleString();$('caseProcessing').textContent=Number(cases.processing||0).toLocaleString();$('caseCompleted').textContent=Number(cases.completed||0).toLocaleString();$('deliveryPending').textContent=Number(delivery.pending||0)+Number(delivery.retry||0);$('deliverySent').textContent=Number(delivery.sent||0).toLocaleString();$('pipelineFailed').textContent=(Number(stats.failed||0)+Number(delivery.failed||0)).toLocaleString();$('pipelineAverage').textContent=Number(stats.average_seconds||0).toFixed(1)+'초';$('pipelineTotal').textContent=Number(stats.total||0).toLocaleString();$('pipelineProcessingTitle').textContent=stats.processing_title||'현재 처리 없음';if($('commonProviderMeta'))$('commonProviderMeta').textContent='Ollama · '+esc(commonProvider.model||'로컬');if($('caseProviderMeta'))$('caseProviderMeta').textContent='OpenRouter · '+Number(caseProvider.attempts||0).toLocaleString()+'/'+Number(caseProvider.soft_limit||800).toLocaleString()}

async function openAnalysis(articleId,caseId){try{var data=await req('/api/poc/master-press/admin/analysis/'+encodeURIComponent(articleId)+'/'+encodeURIComponent(caseId)+'/report');state.analysis={articleId:articleId,caseId:caseId,data:data};var report=data.current||{};var retry=data.reanalysis;var result=retry&&retry.result||{};var components=report.components||{};var evidence=components.evidence_status?evidenceLabel(components.evidence_status):'기록 없음';var status=retry?'<p><b>재분석 상태:</b> '+esc(retry.status)+(retry.error?' · '+esc(retry.error):'')+'</p>':'';$('analysisContent').innerHTML='<p><b>사용 모델:</b> '+esc(report.model||'기록 없음')+'</p><p><b>관련도 / 근거 검증:</b> LLM 원점수 '+Number(components.llm_raw_score!=null?components.llm_raw_score:(report.llm&&report.llm.score)||0).toFixed(0)+'점 · '+esc(evidence)+(components.delivery_eligible===false?' · 발송 제외':'')+'</p><p><b>정규화된 어조:</b> '+esc((report.llm&&report.llm.tone)||'기록 없음')+((report.llm&&report.llm.tone_ambiguous)?' · 복수 응답을 단일값으로 정규화':'')+'</p><p><b>LLM 입력 기사 내용:</b> '+esc((report.input_content&&report.input_content.source)||'기존 기록')+' · 본문 '+Number((report.input_content&&report.input_content.body_length)||0).toLocaleString()+'자 · 요약문 '+Number((report.input_content&&report.input_content.snippet_length)||0).toLocaleString()+'자'+(report.reconstructed?' · 과거 기록을 현재 기사 데이터로 재구성':'')+'</p><h3>점수·근거 검증</h3><pre>'+esc(JSON.stringify({components:components,evidence_validation:report.evidence_validation||{},evidence_candidates:report.input_content&&report.input_content.evidence_candidates||{}},null,2))+'</pre>'+status+(retry&&retry.status==='completed'?'<h3>재분석 결과</h3><pre>'+esc(JSON.stringify(result.analysis_report||result,null,2))+'</pre>':'')+'<h3>시스템 프롬프트</h3><pre>'+esc(report.system_prompt||'기존 분석 기록에는 시스템 프롬프트가 없습니다.')+'</pre><h3>주제 검색 사용자 프롬프트 및 기사 입력</h3><pre>'+esc(report.user_prompt||report.prompt||'초기 분석 기록이 없습니다.')+'</pre><h3>LLM 답변</h3><pre>'+esc(report.raw_response||'초기 분석 기록이 없습니다.')+'</pre>';var models=(data.llm_models&&data.llm_models.length?data.llm_models:(state.llmModels.length?state.llmModels:[report.model,data.selected_llm_model]));$('reanalysisModel').innerHTML=models.filter(Boolean).map(function(model){return '<option value="'+esc(model)+'">'+esc(model)+'</option>'}).join('')||'<option value="">선택 가능한 Ollama 모델이 없습니다.</option>';$('reanalysisModel').value=report.model||data.selected_llm_model||models[0]||'';$('analysisDialog').showModal()}catch(error){toast(error.message)}}
function readyLabel(key){return {naver_news:'네이버 뉴스',kakao_login:'카카오 로그인',token_encryption:'토큰 암호화',supabase:'Supabase',ollama:'Ollama',openrouter:'OpenRouter'}[key]||key}
function organizationName(id){var item=state.organizations.find(function(org){return org.id===id});return item?item.name:'기관 미지정'}
function renderAdmin(data){
  state.cases=data.cases||[];state.organizations=data.organizations||[];state.recipients=data.recipients||[];state.llmModels=(data.settings&&data.settings.llm_models)||[];state.caseLlmModels=(data.settings&&data.settings.case_llm_models)||[];var selected=(data.settings&&data.settings.llm_model)||'',caseSelected=(data.settings&&data.settings.case_llm_model)||'',openrouter=(data.settings&&data.settings.openrouter)||{};$('llmModelSelect').innerHTML=(state.llmModels.length?state.llmModels:[selected]).filter(Boolean).map(function(model){return '<option value="'+esc(model)+'">'+esc(model)+'</option>'}).join('')||'<option value="">Ollama 연결 확인 필요</option>';$('llmModelSelect').value=selected;$('caseLlmModelSelect').innerHTML=(state.caseLlmModels.length?state.caseLlmModels:[caseSelected]).filter(Boolean).map(function(model){return '<option value="'+esc(model)+'">'+esc(model)+'</option>'}).join('')||'<option value="">OpenRouter 무료 모델 확인 필요</option>';$('caseLlmModelSelect').value=caseSelected;$('openrouterModelStatus').textContent=(openrouter.connected?'연결 성공':'연결 실패')+' · 오늘 '+Number(openrouter.attempts||0).toLocaleString()+'/'+Number(openrouter.soft_limit||800).toLocaleString()+'회 · 평균 '+Number(openrouter.average_seconds||0).toFixed(1)+'초';
  $('readiness').innerHTML=Object.entries(data.readiness||{}).map(function(pair){return '<span class="ready-pill '+(pair[1]?'':'off')+'">'+readyLabel(pair[0])+' · '+(pair[1]?'준비':'설정 필요')+'</span>'}).join('');
  $('organizationCount').textContent=state.organizations.length+'개 기관 · '+state.cases.length+'개 케이스';
  var groups=state.organizations.map(function(item){
    var schedule=item.collection_mode==='interval'?item.collection_interval_minutes+'분':(item.collection_times||[]).join(', ');
    var keywordCount=1+(item.abbreviations||[]).length+(item.former_names||[]).length+(item.people||[]).length;
    var organizationStatus='<span class="collection-status '+(item.is_active?'collecting':'stopped')+'">'+(item.is_active?'수집중':'중지')+'</span>';
    var children=state.cases.filter(function(child){return child.organization_id===item.id}).map(function(child){var caseStatus='<span class="collection-status '+(child.is_active?'collecting':'stopped')+'">'+(child.is_active?'수집중':'중지')+'</span>';return '<div class="case-row child-case"><button data-edit="'+child.id+'"><b>'+caseStatus+esc(child.name)+'</b><small>기관 공동 수집 · 기준 '+child.relevance_threshold+'%</small></button><div class="row-actions"><button data-run="'+child.id+'">지금 수집</button><button data-edit="'+child.id+'">설정</button></div></div>'}).join('');
    return '<section class="organization-group"><div class="organization-head"><button data-edit-organization="'+item.id+'"><b>'+organizationStatus+esc(item.name)+'</b><small>'+esc(schedule)+' · 검색어 '+keywordCount+'개 · 소속 '+state.cases.filter(function(child){return child.organization_id===item.id}).length+'개</small></button><div class="row-actions"><button data-new-case-org="'+item.id+'">+ 케이스</button><button data-run-organization="'+item.id+'">기관 수집</button><button data-edit-organization="'+item.id+'">기관 설정</button></div></div><div class="organization-case-list">'+(children||'<div class="empty compact">소속 케이스가 없습니다.</div>')+'</div></section>'
  }).join('');
  var unassigned=state.cases.filter(function(item){return !item.organization_id});
  if(unassigned.length)groups+='<section class="organization-group warning"><div class="organization-head"><b>기관 미지정 케이스</b></div><div class="organization-case-list">'+unassigned.map(function(item){return '<div class="case-row child-case"><button data-edit="'+item.id+'"><b>'+esc(item.name)+'</b><small>기관 지정이 필요합니다.</small></button></div>'}).join('')+'</div></section>';
  $('organizationList').innerHTML=groups||'<div class="empty">사용 기관을 먼저 추가해주세요.</div>';
  $('recipientList').innerHTML=state.recipients.length?state.recipients.map(function(item){var connected=item.connection_status==='connected';return '<div class="recipient-row"><div><b>'+esc(item.label)+'</b><small class="recipient-connection '+(connected?'connected':'failed')+'">'+esc(item.connection_label||(connected?'연결 성공':'연결 실패'))+'</small></div><div class="row-actions"><button data-test="'+item.id+'">테스트</button><button data-remove-recipient="'+item.id+'">해제</button></div></div>'}).join(''):'<div class="empty">카카오 수신자 등록 링크를 생성하세요.</div>';
  $('improvementCase').innerHTML=state.cases.map(function(item){return '<option value="'+item.id+'">'+esc(organizationName(item.organization_id))+' / '+esc(item.name)+'</option>'}).join('')||'<option value="">케이스 없음</option>';
  bindRows();renderRecipientChecks([]);loadImprovement();
}
function bindRows(){
  document.querySelectorAll('[data-edit-organization]').forEach(function(button){button.onclick=function(){openOrganization(state.organizations.find(function(item){return item.id===button.dataset.editOrganization}))}});
  document.querySelectorAll('[data-run-organization]').forEach(function(button){button.onclick=async function(){button.disabled=true;try{var result=await req('/api/poc/master-press/admin/organizations/'+button.dataset.runOrganization+'/run',{method:'POST',body:'{}'});toast('기관 수집 완료 · 신규 '+(result.counts&&result.counts.new||0)+' · 분석 대기 '+(result.counts&&result.counts.analysis_queued||0));await loadAdmin();loadDashboard()}catch(error){toast(error.message)}finally{button.disabled=false}}});

  document.querySelectorAll('[data-new-case-org]').forEach(function(button){button.onclick=function(){openCase(null,button.dataset.newCaseOrg)}});
  document.querySelectorAll('[data-edit]').forEach(function(button){button.onclick=function(){openCase(state.cases.find(function(item){return item.id===button.dataset.edit}))}});
  document.querySelectorAll('[data-run]').forEach(function(button){button.onclick=async function(){button.disabled=true;try{var result=await req('/api/poc/master-press/admin/cases/'+button.dataset.run+'/run',{method:'POST',body:'{}'});toast('수집 완료 · 신규 '+(result.counts&&result.counts.new||0)+' · 분석 대기 '+(result.counts&&result.counts.analysis_queued||0));await loadAdmin()}catch(error){toast(error.message)}finally{button.disabled=false}}});
  document.querySelectorAll('[data-test]').forEach(function(button){button.onclick=async function(){button.disabled=true;try{await req('/api/poc/master-press/admin/recipients/'+button.dataset.test+'/test',{method:'POST',body:'{}'});toast('테스트 메시지를 발송했습니다.');await loadAdmin()}catch(error){toast(error.message)}finally{button.disabled=false}}});
  document.querySelectorAll('[data-remove-recipient]').forEach(function(button){button.onclick=async function(){if(!confirm('수신자 연결과 토큰을 삭제할까요?'))return;try{await req('/api/poc/master-press/admin/recipients/'+button.dataset.removeRecipient,{method:'DELETE'});toast('수신자 연결을 해제했습니다.');loadAdmin()}catch(error){toast(error.message)}}});
}
async function loadAdmin(){try{await req('/api/admin/session');state.isAdmin=true;$('adminGate').hidden=true;$('adminContent').hidden=false;renderAdmin(await req('/api/poc/master-press/admin/bootstrap'))}catch(error){if(error.status===401){state.isAdmin=false;$('adminGate').hidden=false;$('adminContent').hidden=true}else toast(error.message)}}

function renderRecipientChecks(selected){$('caseRecipients').innerHTML=state.recipients.length?state.recipients.map(function(item){return '<label><input type="checkbox" value="'+item.id+'" '+(selected.indexOf(item.id)>=0?'checked':'')+'>'+esc(item.label)+'</label>'}).join(''):'<span>등록된 수신자가 없습니다.</span>'}
function renderOrganizationOptions(selected){$('caseOrganization').innerHTML='<option value="">기관을 선택하세요</option>'+state.organizations.map(function(item){return '<option value="'+item.id+'">'+esc(item.name)+'</option>'}).join('');$('caseOrganization').value=selected||''}
function openCase(item,organizationId){
  organizationId=item&&item.organization_id||organizationId||(state.organizations.length===1?state.organizations[0].id:'');renderOrganizationOptions(organizationId);
  item=item||null;$('caseDialogTitle').textContent=item?'케이스 수정':'새 케이스';$('caseId').value=item&&item.id||'';$('caseName').value=item&&item.name||'';$('caseActive').value=String(item?item.is_active:true);$('caseTopic').value=item&&(item.topic_search_prompt||item.topic_description)||'';$('caseInclude').value=(item&&item.include_terms||[]).join(', ');$('caseRequired').value=(item&&item.required_terms||[]).join(', ');$('caseExclude').value=(item&&item.exclude_terms||[]).join(', ');$('caseUrgent').value=(item&&item.urgent_terms||[]).join(', ');$('collectionMode').value=item&&item.collection_mode||'interval';$('collectionInterval').value=String(item&&item.collection_interval_minutes||30);$('collectionTimes').value=(item&&item.collection_times||[]).join(', ');$('sendRelevantImmediately').value=String(item?item.send_relevant_immediately!==false:true);$('deliveryMode').value=item&&item.delivery_mode||'immediate';$('deliveryTimes').value=(item&&item.delivery_times||[]).join(', ');$('relevanceThreshold').value=item&&item.relevance_threshold!=null?item.relevance_threshold:75;$('holdThreshold').value=item&&item.hold_threshold!=null?item.hold_threshold:55;$('keywordWeight').value=item&&item.keyword_weight!=null?item.keyword_weight:.3;$('semanticWeight').value=item&&item.semantic_weight!=null?item.semantic_weight:.4;$('llmWeight').value=item&&item.llm_weight!=null?item.llm_weight:.3;$('rssUrls').value=(item&&item.rss_urls||[]).join('\n');renderRecipientChecks(item&&item.recipient_ids||[]);$('deleteCase').hidden=!item;$('caseDialog').showModal()
}
function casePayload(){if(!$('caseOrganization').value)throw new Error('사용 기관을 선택하세요.');return {organization_id:$('caseOrganization').value,name:$('caseName').value.trim(),is_active:$('caseActive').value==='true',topic_search_prompt:$('caseTopic').value.trim(),include_terms:csv($('caseInclude').value),required_terms:csv($('caseRequired').value),exclude_terms:csv($('caseExclude').value),urgent_terms:csv($('caseUrgent').value),synonym_terms:{},include_publishers:[],exclude_publishers:[],rss_urls:csv($('rssUrls').value),collection_mode:$('collectionMode').value,collection_interval_minutes:Number($('collectionInterval').value),collection_times:csv($('collectionTimes').value),send_relevant_immediately:$('sendRelevantImmediately').value==='true',delivery_mode:$('deliveryMode').value,delivery_times:csv($('deliveryTimes').value),relevance_threshold:Number($('relevanceThreshold').value),hold_threshold:Number($('holdThreshold').value),keyword_weight:Number($('keywordWeight').value),semantic_weight:Number($('semanticWeight').value),llm_weight:Number($('llmWeight').value),max_articles_per_message:2,recipient_ids:Array.from($('caseRecipients').querySelectorAll('input:checked')).map(function(input){return input.value})}}

$('saveLlmModel').onclick=async function(){var model=$('llmModelSelect').value;if(!model){toast('Ollama 모델을 선택하세요.');return}try{await req('/api/poc/master-press/admin/settings/llm-model',{method:'PUT',body:JSON.stringify({model:model})});toast('다음 LLM 작업부터 '+model+' 모델을 사용합니다.')}catch(error){toast(error.message)}};
$('saveCaseLlmModel').onclick=async function(){var model=$('caseLlmModelSelect').value;if(!model){toast('OpenRouter 무료 모델을 선택하세요.');return}try{var data=await req('/api/poc/master-press/admin/settings/case-llm-model',{method:'PUT',body:JSON.stringify({model:model})});var status=data.openrouter||{};$('openrouterModelStatus').textContent=(status.connected?'연결 성공':'연결 실패')+' · 오늘 '+Number(status.attempts||0).toLocaleString()+'/'+Number(status.soft_limit||800).toLocaleString()+'회';toast('다음 케이스 판정부터 '+model+' 모델을 사용합니다.')}catch(error){toast(error.message)}};
$('reanalyzeButton').onclick=async function(){if(!state.analysis)return;var model=$('reanalysisModel').value;if(!model){toast('재분석 모델을 선택하세요.');return}try{var result=await req('/api/poc/master-press/admin/analysis/'+encodeURIComponent(state.analysis.articleId)+'/'+encodeURIComponent(state.analysis.caseId)+'/reanalyze',{method:'POST',body:JSON.stringify({model:model})});toast('재분석을 대기열에 넣었습니다. 현재 분석 기사 다음에 실행합니다.');var jobId=result.job.id;var timer=setInterval(async function(){try{var report=await req('/api/poc/master-press/admin/analysis/'+encodeURIComponent(state.analysis.articleId)+'/'+encodeURIComponent(state.analysis.caseId)+'/report');var job=report.reanalysis;if(job&&job.id===jobId&&job.status==='completed'){clearInterval(timer);if(confirm('재분석 결과가 나왔습니다. 이번 분석 결과를 반영할까요?')){var applied=await req('/api/poc/master-press/admin/analysis/'+encodeURIComponent(jobId)+'/apply',{method:'POST',body:'{}'});$('analysisDialog').close();loadDashboard(state.activeCase,state.activeOrganization);if(applied.send_eligible&&confirm('추가 알림으로 유사도가 확인되었습니다. 발송하시겠습니까?')){await req('/api/poc/master-press/admin/analysis/'+encodeURIComponent(jobId)+'/send',{method:'POST',body:'{}'});toast('재분석 결과를 반영하고 카카오톡 발송을 요청했습니다.')}else toast('재분석 결과를 반영했습니다.')}else toast('재분석 결과를 반영하지 않았습니다.')}}catch(error){clearInterval(timer);toast(error.message)}},5000)}catch(error){toast(error.message)}};
$('newCase').onclick=function(){if(!state.organizations.length){toast('사용 기관을 먼저 추가해주세요.');return}openCase()};
$('caseForm').onsubmit=async function(event){event.preventDefault();var id=$('caseId').value;try{await req('/api/poc/master-press/admin/cases'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(casePayload())});$('caseDialog').close();toast('케이스 설정을 저장했습니다.');loadAdmin();loadDashboard()}catch(error){toast(error.message)}};
$('deleteCase').onclick=async function(){var id=$('caseId').value;if(!id||!confirm('케이스와 분석 기록을 삭제할까요?'))return;try{await req('/api/poc/master-press/admin/cases/'+id,{method:'DELETE'});$('caseDialog').close();toast('케이스를 삭제했습니다.');loadAdmin();loadDashboard()}catch(error){toast(error.message)}};
function openOrganization(item){
  item=item||null;$('organizationDialogTitle').textContent=item?'기관 수정':'새 기관';$('organizationId').value=item&&item.id||'';$('organizationName').value=item&&item.name||'';$('organizationActive').value=String(item?item.is_active:true);$('organizationAbbreviations').value=(item&&item.abbreviations||[]).join(', ');$('organizationFormerNames').value=(item&&item.former_names||[]).join(', ');$('organizationPeople').value=(item&&item.people||[]).join(', ');$('organizationExcludeTerms').value=(item&&item.exclude_terms||[]).join(', ');$('organizationDomains').value=(item&&item.domains||[]).join(', ');$('organizationRssUrls').value=(item&&item.rss_urls||[]).join('\n');$('organizationCollectionMode').value=item&&item.collection_mode||'interval';$('organizationCollectionInterval').value=String(item&&item.collection_interval_minutes||30);$('organizationCollectionTimes').value=(item&&item.collection_times||[]).join(', ');$('organizationMaxQueries').value=item&&item.max_search_queries||8;$('organizationMaxArticles').value=item&&item.max_articles_per_run||50;$('deleteOrganization').hidden=!item;$('organizationDialog').showModal()
}
function organizationPayload(){return {name:$('organizationName').value.trim(),is_active:$('organizationActive').value==='true',abbreviations:csv($('organizationAbbreviations').value),former_names:csv($('organizationFormerNames').value),people:csv($('organizationPeople').value),exclude_terms:csv($('organizationExcludeTerms').value),domains:csv($('organizationDomains').value),rss_urls:csv($('organizationRssUrls').value),collection_mode:$('organizationCollectionMode').value,collection_interval_minutes:Number($('organizationCollectionInterval').value),collection_times:csv($('organizationCollectionTimes').value),max_search_queries:Number($('organizationMaxQueries').value),max_articles_per_run:Number($('organizationMaxArticles').value)}}
$('newOrganization').onclick=function(){openOrganization()};
$('organizationForm').onsubmit=async function(event){event.preventDefault();var id=$('organizationId').value;try{await req('/api/poc/master-press/admin/organizations'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(organizationPayload())});$('organizationDialog').close();toast('기관 설정을 저장했습니다.');loadAdmin()}catch(error){toast(error.message)}};
$('deleteOrganization').onclick=async function(){var id=$('organizationId').value;if(!id||!confirm('기관을 사용 중지하고 보관할까요? 연결된 기존 통계는 유지됩니다.'))return;try{await req('/api/poc/master-press/admin/organizations/'+id,{method:'DELETE'});$('organizationDialog').close();toast('기관을 중지·보관했습니다.');loadAdmin()}catch(error){toast(error.message)}};


document.querySelectorAll('[data-close]').forEach(function(button){button.onclick=function(){$(button.dataset.close).close()}});

$('newInvite').onclick=function(){$('inviteResult').innerHTML='';$('inviteLabel').value='';$('inviteDialog').showModal()};
$('inviteForm').onsubmit=async function(event){event.preventDefault();try{var data=await req('/api/poc/master-press/admin/invites',{method:'POST',body:JSON.stringify({label:$('inviteLabel').value,ttl_minutes:Number($('inviteTtl').value)})});var url=data.invite.url;$('inviteResult').innerHTML='<b>수신자에게 아래 링크를 전달하세요.</b><p>'+esc(url)+'</p><button type="button" class="small-button" id="copyInvite">링크 복사</button>';$('copyInvite').onclick=async function(){await navigator.clipboard.writeText(url);toast('등록 링크를 복사했습니다.')}}catch(error){toast(error.message)}};
$('runTick').onclick=async function(){var button=$('runTick');button.disabled=true;try{var data=await req('/api/poc/master-press/admin/tick',{method:'POST',body:'{}'});toast('작업 완료 · 기관 '+(data.organizations&&data.organizations.length||0)+' · 기존 케이스 '+(data.cases&&data.cases.length||0)+' · 발송 '+(data.delivery&&data.delivery.sent||0));loadAdmin();loadDashboard()}catch(error){toast(error.message)}finally{button.disabled=false}};

async function loadImprovement(){var id=$('improvementCase').value;if(!id){$('improvementContent').innerHTML='<div class="empty">케이스를 먼저 만드세요.</div>';return}try{var data=await req('/api/poc/master-press/admin/cases/'+id+'/improvements?days=7');var categories=Object.entries(data.categories||{}).sort(function(a,b){return b[1]-a[1]});$('improvementContent').innerHTML='<div class="improvement-score"><span>7일 저점 표본</span><b>'+(data.sample_count||0)+'</b><small>평균 '+Number(data.average_score||0).toFixed(1)+'%</small></div><div><h3>주요 원인</h3><div class="score-parts">'+(categories.map(function(pair){return '<span>'+esc(pair[0])+' '+pair[1]+'</span>'}).join('')||'<span>분석 대기</span>')+'</div><h3>설정 개선 제안</h3><ul>'+((data.suggestions||[]).map(function(item){return '<li>'+esc(item)+'</li>'}).join('')||'<li>데이터가 쌓이면 사례별 제안을 표시합니다.</li>')+'</ul></div>'}catch(error){toast(error.message)}}
$('improvementCase').onchange=loadImprovement;
function renderRefreshCountdown(){var label=$('refreshCountdown');if(!label)return;if(!state.refreshSeconds){label.textContent='(다음 갱신: 안함)';return}var minute=Math.floor(state.refreshRemaining/60);var second=state.refreshRemaining%60;label.textContent='(다음 갱신: '+String(minute).padStart(2,'0')+':'+String(second).padStart(2,'0')+'초)'}
function startAutoRefresh(){clearInterval(state.countdownTimer);state.refreshSeconds=Number($('refreshInterval').value);state.refreshRemaining=state.refreshSeconds;renderRefreshCountdown();if(!state.refreshSeconds)return;state.countdownTimer=setInterval(function(){if($('dashboardView').hidden)return;state.refreshRemaining-=1;if(state.refreshRemaining<=0){state.refreshRemaining=state.refreshSeconds;loadDashboard(state.activeCase,state.activeOrganization)}renderRefreshCountdown()},1000)}
$('refreshInterval').onchange=startAutoRefresh;
startAutoRefresh();
if(new URLSearchParams(location.search).get('admin')==='1')showView('admin');else loadDashboard();
if(new URLSearchParams(location.search).get('connected')==='1')toast('카카오 수신자 등록이 완료되었습니다.');
