"""Standalone administrator page served by the main ASGI application."""

ADMIN_HTML = r"""<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>MinsLab 관리자</title>
  <style>
    :root{color-scheme:light;--ink:#171916;--muted:#697067;--line:#d6d4ca;--paper:#fffdf6;--bg:#f3f1e9;--accent:#7054ef;--lime:#dfff56;--danger:#c84736}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,"Segoe UI",sans-serif}button,input{font:inherit}
    .topbar{height:68px;padding:0 max(18px,calc((100% - 1180px)/2));display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);background:rgba(243,241,233,.94);position:sticky;top:0;z-index:5}.brand{display:flex;align-items:center;gap:10px;font-weight:900}.brand i{width:32px;height:32px;display:grid;place-items:center;border-radius:10px 10px 50% 50%;background:var(--ink);color:var(--lime);font-style:normal}.topbar a{color:var(--muted);font-size:12px;text-decoration:none}
    .login-shell{min-height:calc(100vh - 68px);display:grid;place-items:center;padding:24px}.login-card{width:min(100%,420px);padding:32px;border:1px solid var(--ink);border-radius:20px;background:var(--paper);box-shadow:8px 8px 0 var(--lime)}.kicker{color:var(--accent);font:700 11px ui-monospace,monospace;letter-spacing:.1em}.login-card h1{margin:12px 0 8px;font-size:32px}.login-card p{margin:0 0 22px;color:var(--muted);line-height:1.65;font-size:14px}.field{display:grid;gap:7px;color:#555b52;font-size:12px;font-weight:800}.field input{width:100%;padding:13px;border:1px solid var(--line);border-radius:11px;background:#fff}.primary{min-height:44px;padding:0 16px;border:0;border-radius:11px;background:var(--ink);color:var(--lime);font-weight:850;cursor:pointer}.login-card .primary{width:100%;margin-top:12px}.message{min-height:20px;margin-top:12px;color:var(--danger);font-size:12px}
    .admin{max-width:1180px;margin:auto;padding:34px 18px 70px}.admin-head{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:24px}.admin-head h1{margin:8px 0 0;font-size:clamp(30px,4vw,48px);letter-spacing:-.04em}.secondary{padding:9px 13px;border:1px solid var(--line);border-radius:10px;background:var(--paper);cursor:pointer}.tabs{display:flex;gap:6px;padding:4px;width:max-content;border:1px solid var(--line);border-radius:99px;margin-bottom:22px}.tab{padding:9px 15px;border:0;border-radius:99px;background:transparent;color:var(--muted);font-size:12px;font-weight:800}.tab.active{background:var(--ink);color:#fff}.tab:disabled{opacity:.45}
    .stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:9px;margin-bottom:18px}.stat{padding:14px 15px;border:1px solid var(--line);border-radius:13px;background:var(--paper);min-width:0}.stat span{display:block;color:var(--muted);font-size:10px;font-weight:800}.stat b{display:block;margin-top:6px;font-size:23px}.stat.runtime{grid-column:span 2}.stat.runtime b{font:800 14px ui-monospace,monospace;white-space:nowrap}.panel{border:1px solid var(--line);border-radius:18px;background:var(--paper);overflow:hidden}.panel-head{padding:17px 18px;display:flex;justify-content:space-between;gap:14px;align-items:center;border-bottom:1px solid var(--line)}.panel-head h2{margin:0;font-size:17px}.filters{display:flex;gap:8px;flex-wrap:wrap}.filters input{min-height:38px;padding:0 10px;border:1px solid var(--line);border-radius:9px;background:#fff;font-size:12px}.filters .primary{min-height:38px}
    .resource-panel{margin-bottom:18px;padding:17px 18px 14px;border:1px solid var(--line);border-radius:18px;background:var(--paper)}.resource-title{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin-bottom:13px}.resource-title h2{margin:0;font-size:17px}.resource-title span{color:var(--muted);font:11px ui-monospace,monospace}.resource-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.resource-card{min-width:0;padding:14px;border:1px solid #e3e0d6;border-radius:13px;background:#faf9f4}.metric-head{display:flex;align-items:end;justify-content:space-between;gap:12px}.metric-head span{display:block;color:var(--muted);font-size:10px;font-weight:900;letter-spacing:.08em}.metric-head b{display:block;margin-top:4px;font-size:25px}.metric-head small{color:var(--muted);font-size:10px;text-align:right}.metric-chart{display:block;width:100%;height:150px;margin-top:10px;overflow:visible}.metric-axis{display:flex;justify-content:space-between;color:#8a9088;font:9px ui-monospace,monospace}.metric-empty{fill:#8a9088;font:12px sans-serif}
    .path-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:9px;padding:14px 18px;border-bottom:1px solid var(--line)}.path-card{padding:11px;border:1px solid #e3e0d6;border-radius:11px;background:#faf9f4;min-width:0}.path-card b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}.path-card span{display:block;margin-top:5px;color:var(--muted);font-size:11px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:840px}th,td{padding:12px 14px;border-bottom:1px solid #e8e5dc;text-align:left;font-size:12px;vertical-align:top}th{color:var(--muted);font-size:10px;letter-spacing:.04em;background:#faf9f4}.path-cell{max-width:280px;word-break:break-all}.agent-cell{max-width:280px;color:var(--muted);word-break:break-word}.empty{text-align:center!important;color:var(--muted);padding:36px!important}.pager{display:flex;align-items:center;justify-content:center;gap:12px;padding:14px}.pager span{font-size:12px;color:var(--muted)}[hidden]{display:none!important}
    @media(max-width:800px){.stats{grid-template-columns:1fr 1fr}.resource-grid{grid-template-columns:1fr}.admin-head{align-items:start}.panel-head{align-items:stretch;flex-direction:column}.filters{display:grid;grid-template-columns:1fr 1fr}.filters input:first-child{grid-column:1/-1}.filters .primary{grid-column:1/-1}.path-grid{grid-template-columns:1fr}.topbar{padding-inline:14px}.admin{padding-inline:14px}}@media(max-width:440px){.stats{grid-template-columns:1fr}.stat.runtime{grid-column:auto}.resource-title{display:block}.resource-title span{display:block;margin-top:5px}.admin-head{display:grid}.admin-head .secondary{width:max-content}.tabs{width:100%}.tab{flex:1}}
  </style>
</head>
<body>
  <header class="topbar"><div class="brand"><i>M</i>MinsLab Admin</div><a href="/">홈페이지로 돌아가기 ↗</a></header>
  <main class="login-shell" id="loginView">
    <form class="login-card" id="loginForm"><span class="kicker">ADMINISTRATOR</span><h1>관리자 로그인</h1><p>방문 통계와 향후 홈페이지 설정을 관리하는 전용 화면입니다.</p><label class="field">관리자 암호<input id="password" type="password" autocomplete="current-password" required autofocus></label><button class="primary" id="loginButton" type="submit">로그인</button><div class="message" id="loginMessage" role="alert"></div></form>
  </main>
  <main class="admin" id="adminView" hidden>
    <div class="admin-head"><div><span class="kicker">MINSLAB / CONTROL PANEL</span><h1>운영 대시보드</h1></div><button class="secondary" id="logoutButton" type="button">로그아웃</button></div>
    <nav class="tabs" aria-label="관리자 메뉴"><button class="tab active" type="button">방문 통계</button><button class="tab" type="button" disabled title="향후 제공 예정">사이트 설정</button></nav>
    <section class="stats"><article class="stat"><span>전체 조회</span><b id="totalViews">0</b></article><article class="stat"><span>오늘 조회</span><b id="todayViews">0</b></article><article class="stat"><span>오늘 방문자</span><b id="todayVisitors">0</b></article><article class="stat"><span>Local LLM 호출</span><b id="localLlmCalls">0</b></article><article class="stat runtime"><span>가동 시간</span><b id="runtime">-</b></article></section>
    <section class="resource-panel"><div class="resource-title"><h2>서버 리소스 · 최근 3일</h2><span id="metricRange">수집 내역 확인 중</span></div><div class="resource-grid"><article class="resource-card"><div class="metric-head"><div><span>CPU USAGE</span><b id="cpuCurrent">-</b></div><small id="cpuSummary">평균 - · 최대 -</small></div><svg class="metric-chart" id="cpuChart" viewBox="0 0 720 150" preserveAspectRatio="none" role="img" aria-label="최근 3일 CPU 사용률"></svg><div class="metric-axis"><span>3일 전</span><span>현재</span></div></article><article class="resource-card"><div class="metric-head"><div><span>MEM USAGE</span><b id="memoryCurrent">-</b></div><small id="memorySummary">평균 - · 최대 -</small></div><svg class="metric-chart" id="memoryChart" viewBox="0 0 720 150" preserveAspectRatio="none" role="img" aria-label="최근 3일 메모리 사용률"></svg><div class="metric-axis"><span>3일 전</span><span>현재</span></div></article></div></section>
    <section class="panel"><div class="panel-head"><h2>방문 기록</h2><form class="filters" id="filterForm"><input id="dateFilter" type="date" aria-label="날짜"><input id="ipFilter" placeholder="IP 검색" maxlength="80"><input id="pathFilter" placeholder="방문 페이지 검색" maxlength="200"><button class="primary" type="submit">조회</button></form></div><div class="path-grid" id="pathStats"></div><div class="table-wrap"><table><thead><tr><th>방문 시각</th><th>IP</th><th>방문 페이지</th><th>유입 경로</th><th>브라우저</th></tr></thead><tbody id="visitRows"></tbody></table></div><div class="pager"><button class="secondary" id="prevPage" type="button">이전</button><span id="pageLabel">1 / 1</span><button class="secondary" id="nextPage" type="button">다음</button></div></section>
  </main>
  <script>
    const $=id=>document.getElementById(id),loginView=$('loginView'),adminView=$('adminView'),loginForm=$('loginForm'),loginMessage=$('loginMessage'),passwordInput=$('password'),loginButton=$('loginButton'),logoutButton=$('logoutButton'),filterForm=$('filterForm'),dateFilter=$('dateFilter'),ipFilter=$('ipFilter'),pathFilter=$('pathFilter'),totalViews=$('totalViews'),todayViews=$('todayViews'),todayVisitors=$('todayVisitors'),localLlmCalls=$('localLlmCalls'),runtime=$('runtime'),metricRange=$('metricRange'),cpuCurrent=$('cpuCurrent'),cpuSummary=$('cpuSummary'),cpuChart=$('cpuChart'),memoryCurrent=$('memoryCurrent'),memorySummary=$('memorySummary'),memoryChart=$('memoryChart'),pathStats=$('pathStats'),visitRows=$('visitRows'),pageLabel=$('pageLabel'),prevPage=$('prevPage'),nextPage=$('nextPage');let page=1,pages=1;
    const number=value=>Number(value||0).toLocaleString('ko-KR');
    function uptimeText(seconds){seconds=Math.max(0,Number(seconds||0));const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60);return days?`${days}d ${hours}h`:hours?`${hours}h ${minutes}m`:minutes?`${minutes}m`:`${Math.floor(seconds)}s`}
    async function request(url,options={}){const response=await fetch(url,{cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(!response.ok){const error=new Error(data.error||'요청을 처리하지 못했습니다.');error.status=response.status;throw error}return data}
    function showLogin(message=''){loginView.hidden=false;adminView.hidden=true;loginMessage.textContent=message;document.getElementById('password').focus()}
    function showAdmin(){loginView.hidden=true;adminView.hidden=false}
    function appendCell(row,text,className=''){const cell=document.createElement('td');cell.textContent=text||'-';if(className)cell.className=className;row.append(cell)}
    function percent(value){if(value===null||value===undefined||value==='')return'-';const numeric=Number(value);return Number.isFinite(numeric)?`${numeric.toFixed(1)}%`:'-'}
    function renderMetricChart(svg,metrics,key,color){const points=(metrics.points||[]).map(item=>({time:Date.parse(item.sampled_at),value:Math.max(0,Math.min(100,Number(item[key])))})).filter(item=>Number.isFinite(item.time)&&Number.isFinite(item.value)),start=Date.parse(metrics.range_started_at),end=Date.parse(metrics.range_ended_at),duration=Math.max(1,end-start),coords=points.map(item=>`${Math.max(0,Math.min(720,((item.time-start)/duration)*720)).toFixed(2)},${(145-item.value*1.35).toFixed(2)}`),grid=[10,43.75,77.5,111.25,145].map(y=>`<line x1="0" y1="${y}" x2="720" y2="${y}" stroke="#dedbd1" stroke-width="1"/>`).join('');if(!coords.length){svg.innerHTML=`${grid}<text class="metric-empty" x="360" y="80" text-anchor="middle">지표 수집을 시작했습니다.</text>`;return}const area=`0,145 ${coords.join(' ')} 720,145`;svg.innerHTML=`${grid}<polyline points="${area}" fill="${color}" opacity=".10" stroke="none"/><polyline points="${coords.join(' ')}" fill="none" stroke="${color}" stroke-width="2.5" vector-effect="non-scaling-stroke"/>${coords.length===1?`<circle cx="${coords[0].split(',')[0]}" cy="${coords[0].split(',')[1]}" r="4" fill="${color}"/>`:''}`}
    function renderSystemMetrics(metrics,interval){const cpu=metrics.cpu||{},memory=metrics.memory||{},points=metrics.points||[];cpuCurrent.textContent=percent(cpu.current);cpuSummary.textContent=`평균 ${percent(cpu.average)} · 최대 ${percent(cpu.maximum)}`;memoryCurrent.textContent=percent(memory.current);memorySummary.textContent=`평균 ${percent(memory.average)} · 최대 ${percent(memory.maximum)}`;renderMetricChart(cpuChart,metrics,'cpu_percent','#7054ef');renderMetricChart(memoryChart,metrics,'memory_percent','#4b9d68');const start=new Date(metrics.range_started_at),end=new Date(metrics.range_ended_at),minutes=Math.max(1,Math.round(Number(interval||60)/60));metricRange.textContent=Number.isFinite(start.getTime())?`${start.toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} — ${end.toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} · ${minutes}분 간격 · ${number(points.length)}개`:'수집 내역 없음'}
    function render(data){const summary=data.summary||{};totalViews.textContent=number(summary.total_views);todayViews.textContent=number(summary.today_views);todayVisitors.textContent=number(summary.today_visitors);localLlmCalls.textContent=number(summary.local_llm_calls);const webTime=uptimeText(data.web_uptime_seconds??data.uptime_seconds),serverTime=data.host_uptime_seconds==null?'-':uptimeText(data.host_uptime_seconds);runtime.textContent=`WEB ${webTime} · SERVER ${serverTime}`;renderSystemMetrics(data.system_metrics||{},data.system_metrics_interval_seconds);dateFilter.value=data.visits?.date||dateFilter.value;pathStats.replaceChildren();for(const item of data.visits?.paths||[]){const card=document.createElement('div');card.className='path-card';const path=document.createElement('b'),meta=document.createElement('span');path.textContent=item.path;path.title=item.path;meta.textContent=`조회 ${number(item.views)} · 방문자 ${number(item.visitors)}`;card.append(path,meta);pathStats.append(card)}if(!pathStats.childElementCount){const empty=document.createElement('div');empty.className='path-card';empty.textContent='선택한 날짜의 방문 기록이 없습니다.';pathStats.append(empty)}visitRows.replaceChildren();for(const item of data.visits?.items||[]){const row=document.createElement('tr');appendCell(row,new Date(item.visited_at).toLocaleString('ko-KR'));appendCell(row,item.ip_address);appendCell(row,item.path,'path-cell');appendCell(row,item.referrer,'path-cell');appendCell(row,item.user_agent,'agent-cell');visitRows.append(row)}if(!visitRows.childElementCount){const row=document.createElement('tr'),cell=document.createElement('td');cell.colSpan=5;cell.className='empty';cell.textContent='방문 기록이 없습니다.';row.append(cell);visitRows.append(row)}const pagination=data.visits?.pagination||{};page=Number(pagination.page||1);pages=Number(pagination.pages||1);pageLabel.textContent=`${page} / ${pages} · ${number(pagination.total)}건`;prevPage.disabled=page<=1;nextPage.disabled=page>=pages}
    async function loadAnalytics(targetPage=1){try{const params=new URLSearchParams({page:String(targetPage),page_size:'50'});if(dateFilter.value)params.set('date',dateFilter.value);if(ipFilter.value.trim())params.set('ip',ipFilter.value.trim());if(pathFilter.value.trim())params.set('path',pathFilter.value.trim());const data=await request(`/api/admin/analytics?${params}`);showAdmin();render(data)}catch(error){if(error.status===401)showLogin('로그인이 필요합니다.');else alert(error.message)}}
    loginForm.addEventListener('submit',async event=>{event.preventDefault();loginMessage.textContent='확인 중...';loginButton.disabled=true;try{await request('/api/admin/login',{method:'POST',body:JSON.stringify({password:passwordInput.value})});passwordInput.value='';await loadAnalytics(1)}catch(error){showLogin(error.message)}finally{loginButton.disabled=false}});
    logoutButton.addEventListener('click',async()=>{try{await request('/api/admin/logout',{method:'POST',body:'{}'})}finally{showLogin('로그아웃되었습니다.')}});filterForm.addEventListener('submit',event=>{event.preventDefault();loadAnalytics(1)});prevPage.addEventListener('click',()=>loadAnalytics(page-1));nextPage.addEventListener('click',()=>loadAnalytics(page+1));
    request('/api/admin/session').then(()=>loadAnalytics(1)).catch(()=>showLogin());
  </script>
</body>
</html>"""
