/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportWeeklyRouteImport } from './routes/report.weekly'
import { Route as ReportMonthlyRouteImport } from './routes/report.monthly'
import { Route as ReportTaskTaskIdRouteImport } from './routes/report.task.$taskId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportWeeklyRoute = ReportWeeklyRouteImport.update({
  id: '/report/weekly',
  path: '/report/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportMonthlyRoute = ReportMonthlyRouteImport.update({
  id: '/report/monthly',
  path: '/report/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTaskTaskIdRoute = ReportTaskTaskIdRouteImport.update({
  id: '/report/task/$taskId',
  path: '/report/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/report/monthly': typeof ReportMonthlyRoute
  '/report/weekly': typeof ReportWeeklyRoute
  '/report/task/$taskId': typeof ReportTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/report/monthly': typeof ReportMonthlyRoute
  '/report/weekly': typeof ReportWeeklyRoute
  '/report/task/$taskId': typeof ReportTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/report/monthly': typeof ReportMonthlyRoute
  '/report/weekly': typeof ReportWeeklyRoute
  '/report/task/$taskId': typeof ReportTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/report/monthly'
    | '/report/weekly'
    | '/report/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/report/monthly'
    | '/report/weekly'
    | '/report/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/report/monthly'
    | '/report/weekly'
    | '/report/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ReportMonthlyRoute: typeof ReportMonthlyRoute
  ReportWeeklyRoute: typeof ReportWeeklyRoute
  ReportTaskTaskIdRoute: typeof ReportTaskTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/weekly': {
      id: '/report/weekly'
      path: '/report/weekly'
      fullPath: '/report/weekly'
      preLoaderRoute: typeof ReportWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/monthly': {
      id: '/report/monthly'
      path: '/report/monthly'
      fullPath: '/report/monthly'
      preLoaderRoute: typeof ReportMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/task/$taskId': {
      id: '/report/task/$taskId'
      path: '/report/task/$taskId'
      fullPath: '/report/task/$taskId'
      preLoaderRoute: typeof ReportTaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ReportMonthlyRoute: ReportMonthlyRoute,
  ReportWeeklyRoute: ReportWeeklyRoute,
  ReportTaskTaskIdRoute: ReportTaskTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
