from __future__ import annotations

import json
import unittest
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parents[2]


class WebDashboardTests(unittest.TestCase):
    def test_operational_shell_forces_current_report_assets(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        security = (
            PROJECT_DIR / "backend/app/services/web_security.py"
        ).read_text(encoding="utf-8")
        self.assertIn("assets/app.js?v=20260917-2", html)
        self.assertIn("assets/workspace.css?v=20260917-4", html)
        self.assertIn('response.headers["Cache-Control"] = "no-store, max-age=0"', security)
        self.assertIn('path.startswith("/assets/")', security)

    def test_meeting_report_list_is_lightweight_and_detail_has_loading_state(self):
        script = (PROJECT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        api = (PROJECT_DIR / "backend/app/main.py").read_text(encoding="utf-8")
        repository = (
            PROJECT_DIR / "backend/app/db/meeting_brief_repository.py"
        ).read_text(encoding="utf-8")

        self.assertIn("const MEETING_HISTORY_INITIAL_LIMIT = 5;", script)
        self.assertIn("const MEETING_HISTORY_PAGE_SIZE = 5;", script)
        self.assertIn("회의 보고서를 불러오는 중입니다", script)
        self.assertIn("meetingReportLoadingVisual", script)
        self.assertIn("REPORT DATA PIPELINE · ACTIVE", script)
        self.assertIn("const meetingBriefRequests = new Map();", script)
        self.assertIn("if (liveStatusLoadPromise) return liveStatusLoadPromise;", script)
        self.assertIn("if (!meetingRailHistoryState.initialized) return false;", script)
        self.assertIn("latest_summary_map", api)
        self.assertIn("include_content=False", api)
        self.assertIn("jsonb_build_object", repository)

    def test_extras_workspace_has_calendar_and_government_flow_insights(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        script = (PROJECT_DIR / "web" / "assembly-extras.js").read_text(encoding="utf-8")
        styles = (PROJECT_DIR / "web" / "assembly-extras.css").read_text(encoding="utf-8")
        app = (PROJECT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        self.assertIn("인사이트", html)
        self.assertNotIn('data-workspace-tab="extras"><b>추가기능</b>', html)
        self.assertIn('data-workspace-tab="extras"', html)
        self.assertIn('data-workspace-panel="extras"', html)
        self.assertIn("국회 일정 달력", html)
        self.assertNotIn('id="assemblyReferenceTitle"', html)
        self.assertNotIn('id="assemblyHemicycleTitle"', html)
        self.assertNotIn("정당별 의석 구성", html)
        self.assertIn("LLM 0회", html)
        self.assertIn('id="assemblyOntologyOpen"', html)
        self.assertIn('id="assemblyOntologyDialog"', html)
        self.assertIn('id="assemblyOntologyCanvas"', html)
        self.assertIn("국정 온톨로지 3D 스타맵", html)
        self.assertIn('import("./ontology-starmap.js?v=20260917-4")', script)
        self.assertIn("api/policy/ontology", script)
        self.assertIn('ontologyMetric("분류된 주제", `${Number(metrics.ontology_topic_count || 0).toLocaleString()}건`)', script)
        self.assertIn('ontologyMetric("온톨로지 적용률", `${coverage.toFixed(1)}%`', script)
        self.assertNotIn('`${Number(metrics.ontology_topic_count || 0).toLocaleString()} · ${coverage}%`', script)
        self.assertIn("grid-template-columns:repeat(6,minmax(0,1fr))", styles)
        self.assertIn("specific-issues?limit=80", script)
        self.assertIn("Promise.allSettled", script)
        self.assertIn(".assembly-ontology-dialog", styles)
        self.assertIn("drawOntology", script)
        three = (PROJECT_DIR / "web" / "ontology-starmap.js").read_text(encoding="utf-8")
        self.assertIn('import * as THREE from "./vendor/three.module.js"', three)
        self.assertIn("new THREE.WebGLRenderer", three)
        self.assertIn("THREE.PerspectiveCamera", three)
        self.assertIn("THREE.Raycaster", three)
        self.assertIn("label.visible = false", three)
        self.assertIn("select: selectByKey", three)
        self.assertIn("ontologyState.scene3d?.select(item.key)", script)
        self.assertIn("background:#fff", styles)
        self.assertTrue((PROJECT_DIR / "web" / "vendor" / "three.module.js").is_file())
        self.assertTrue((PROJECT_DIR / "web" / "vendor" / "three.core.js").is_file())
        self.assertTrue((PROJECT_DIR / "web" / "vendor" / "THREE-LICENSE.txt").is_file())
        self.assertIn('hash === "extras"', app)
        self.assertIn("displayRange", script)
        self.assertIn("data-calendar-filter", html)
        self.assertIn("assembly-extras-grid", styles)
        self.assertIn("assembly-schedule-layout", html)
        self.assertIn("grid-template-columns:minmax(0,2fr) minmax(280px,1fr)", styles)
        self.assertIn("overflow-y:scroll", styles)
        self.assertIn("height:min(760px,max(620px,calc(100vh - 180px)))", styles)
        self.assertEqual(html.count(">국정 흐름 인사이트<"), 1)
        self.assertLess(html.index('id="assemblyInsightsTitle"'), html.index('id="assemblyCalendarTitle"'))
        self.assertLess(html.index('id="assemblyCalendarTitle"'), html.index('id="assemblyDayAgendaTitle"'))
        self.assertIn("grid-column:1 / -1", styles)
        self.assertIn("@media (max-width:620px)", styles)
        self.assertIn("의원실 일정", script)
        self.assertIn("위원회 일정", script)
        self.assertIn(
            '[["국무회의 일정", executiveItems], ["위원회 일정", committeeItems], ["의원실 일정", memberItems]]',
            script,
        )
        self.assertIn("국무회의·국회 일정 달력", html)
        self.assertIn("● 방송예정", script)
        self.assertIn("● 방송 완료", script)
        self.assertIn("is-completed", styles)
        self.assertIn("function isExecutiveSchedule", script)
        self.assertNotIn("    loadReference();", script)
        self.assertIn("function isCommitteeSchedule", script)
        self.assertIn('String(item?.schedule_kind || "") === "위원회"', script)
        self.assertIn("정책 흐름 타임라인", html)
        self.assertIn("지속·급증·소멸 쟁점", html)
        self.assertIn("논의 → 제도화 전환", html)
        self.assertIn("renderPolicyTimeline", script)
        self.assertIn("renderIssueTrends", script)
        self.assertIn("renderInstitutionFlow", script)
        self.assertIn("api/policy/specific-issues", script)
        self.assertIn("어떤 회의에서 논의됐나", script)
        self.assertIn("어떤 의안으로 상정됐나", script)
        self.assertIn("어떤 절차를 거쳐 어디까지 왔나", script)
        self.assertNotIn('fetch("api/committees/policy-flow"', script)
        self.assertIn("구체 주제 · 최근 14일 비교", html)
        self.assertIn("구체 주제 · 과제·의결·의안", html)
        self.assertIn("item.trend_status", script)
        self.assertIn('item.transition_stage !== "DISCUSSION"', script)
        self.assertIn("법안 언급 · 발의 확인 아님", script)
        self.assertIn("의안번호 미연결 · 발의 확인 아님", script)
        self.assertIn('id="assemblyInsightDialog"', html)
        self.assertIn('aria-labelledby="assemblyInsightDialogTitle"', html)
        self.assertIn("openPolicyComparison", script)
        self.assertIn("openTopicSummary", script)
        self.assertIn('makeInsightInteractive(card, () => openPolicyComparison(item))', script)
        self.assertIn('makeInsightInteractive(row, () => openTopicSummary(item, "trend"))', script)
        self.assertIn('makeInsightInteractive(row, () => openTopicSummary(item, "institution"))', script)
        self.assertIn("정부 · 국무회의 공식 자료", script)
        self.assertIn("국회 · 회의 보고서", script)
        self.assertIn(".assembly-insight-compare-grid", styles)
        self.assertIn("grid-template-columns:1fr 1fr", styles)
        self.assertIn(".assembly-insight-dialog::backdrop", styles)
        self.assertIn("font-size:15px", styles)
        self.assertIn("font-size:13px", styles)

    def test_gukjeong_on_brand_uses_local_small_logo(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        workspace = (PROJECT_DIR / "web" / "workspace.css").read_text(encoding="utf-8")
        self.assertIn("<title>국정ON</title>", html)
        self.assertIn('aria-label="국정ON 홈"', html)
        self.assertIn('src="assets/images/gukjeong-on-small.png"', html)
        self.assertIn(".brand-logo", workspace)
        self.assertTrue((PROJECT_DIR / "web" / "images" / "gukjeong-on-small.png").is_file())
        self.assertTrue((PROJECT_DIR / "web" / "images" / "gukjeong-on.png").is_file())

    def test_meeting_report_selection_survives_reload_but_first_visit_uses_latest(self):
        script = (PROJECT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        self.assertIn('const MEETING_REPORT_QUERY_KEY = "report"', script)
        self.assertIn("url.searchParams.set(MEETING_REPORT_QUERY_KEY, value)", script)
        self.assertIn('navigation?.type !== "reload"', script)
        self.assertIn("window.sessionStorage.getItem(MEETING_REPORT_SELECTION_KEY)", script)
        self.assertIn("rememberMeetingReportSelection(card.id)", script)
        self.assertIn("row.dataset.broadcastId === preferredId", script)
        self.assertIn(
            "while (preferredId && !target && meetingRailHistoryState.hasMore)",
            script,
        )
        self.assertIn("target ||= rows[0]", script)
        self.assertIn("sortMeetingReportCards(reportContainer)", script)
        self.assertIn("const preserveReportScroll = !latestMeetingReportState.pending", script)
        self.assertIn("const selectionId = meeting.live_capture?.broadcast_id", script)
        self.assertIn("assemblyTranscriptState.selectedBroadcastId = selectionId", script)

    def test_topic_report_uses_consistent_editorial_layout(self):
        script = (PROJECT_DIR / "web" / "topic-reports.js").read_text(encoding="utf-8")
        styles = (PROJECT_DIR / "web" / "topic-reports.css").read_text(encoding="utf-8")
        self.assertIn('node("b", "", "국정ON")', script)
        self.assertIn("국정ON editorial desk", styles)
        self.assertIn("border-bottom:5px double #172b46", styles)
        self.assertIn("SPECIAL POLICY EDITION", styles)
        self.assertIn('.topic-report-hero p::first-letter', styles)
        self.assertIn("height: auto", styles)
        self.assertIn("min-height: 300px", styles)
        self.assertIn("max-height:252px", styles)
        self.assertNotIn('content: "POLICY · PARLIAMENT · GOVERNMENT"', styles)

    def test_meeting_report_has_cached_official_change_summary(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        app = (PROJECT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        api = (PROJECT_DIR / "backend/app/main.py").read_text(encoding="utf-8")
        repository = (
            PROJECT_DIR / "backend/app/db/live_repository.py"
        ).read_text(encoding="utf-8")
        integration = (PROJECT_DIR / "web" / "official-integration.js").read_text(encoding="utf-8")
        styles = (PROJECT_DIR / "web" / "workspace.css").read_text(encoding="utf-8")
        self.assertNotIn("결과 권위", html)
        self.assertIn("비공식·공식 결과 통합", html)
        self.assertIn("renderOfficialChangeReport", integration)
        self.assertIn("FULL_REWRITE_SUPPRESSED", integration)
        self.assertIn("official-change-toggle", integration)
        self.assertIn('toggle.setAttribute("aria-expanded", "false")', integration)
        self.assertIn('list.hidden = true', integration)
        self.assertIn("상세 내용 펼치기", integration)
        self.assertIn("official_change_report", app)
        self.assertIn('!= "TEMPORARY_UPDATE_DEFERRED"', api)
        self.assertIn("if not integration or integration_deferred", api)
        self.assertIn("official-change-report", styles)
        self.assertIn('.official-change-toggle[aria-expanded="true"]', styles)
        self.assertIn("Boolean(ended.official_integration_updated_at)", app)
        self.assertIn("official_comparison_progress", app)
        self.assertIn("`공식대조중(${Math.round(comparisonProgress)}%)`", app)
        self.assertIn("official_comparison_progress", repository)

    def test_alarm_live_and_reports_are_separate_top_level_workspaces(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        script = (PROJECT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        watch_script = (PROJECT_DIR / "web" / "watch-alerts.js").read_text(encoding="utf-8")
        styles = (PROJECT_DIR / "web" / "watch-alerts.css").read_text(encoding="utf-8")
        workspace_styles = (PROJECT_DIR / "web" / "workspace.css").read_text(encoding="utf-8")

        self.assertIn('data-workspace-tab="live"><i aria-hidden="true"></i><b>알람·실시간</b>', html)
        self.assertIn('data-workspace-tab="reports"><b>회의 보고서</b>', html)
        self.assertIn('data-workspace-panel="reports"', html)
        self.assertIn('id="liveAlertMount"', html)
        self.assertIn('id="liveOperationsExpandedStage"', html)
        self.assertIn('id="reportBroadcastRows"', html)
        self.assertIn("실시간 초안 보고서", script)
        self.assertIn("requestLatestMeetingReport", script)
        self.assertIn("openLatestMeetingReport", script)
        self.assertIn('openLatest: tab.dataset.workspaceTab === "reports"', script)
        self.assertIn("dataset.reportTimestamp", script)
        meeting_brief = script.split("function expandMeetingBrief(", 1)[1].split(
            "function expandEndedBroadcast(", 1,
        )[0]
        self.assertNotIn("scrollIntoView", meeting_brief)
        ended_executive = script.split(
            "function expandEndedExecutiveBroadcast(", 1,
        )[1].split("function meetingBriefStatusLabel(", 1)[0]
        self.assertNotIn("scrollIntoView", ended_executive)
        report_handoff = script.split("const openReportWorkspace = () =>", 1)[1].split(
            "if (!hasReportResult)", 1,
        )[0]
        self.assertNotIn("scrollIntoView", report_handoff)
        self.assertIn('"meeting-brief-view live-draft-report"', script)
        self.assertIn('"meeting-brief-hero"', script)
        self.assertIn('"meeting-topic-task-overview live-draft-overview"', script)
        self.assertIn('"meeting-result-topic live-draft-result-topic"', script)
        self.assertIn("function liveDraftTopicMetadata(group, entries)", script)
        self.assertIn('"live-draft-topic-metadata"', script)
        self.assertNotIn('entries.slice(-3).map((entry) => entry.summary).join(" ")', script)
        self.assertIn(".live-draft-topic-metadata", workspace_styles)
        self.assertIn("실시간 초안 · 잠정", script)
        self.assertIn("도출 과제", script)
        self.assertIn("focusLiveDraftEvidence", script)
        self.assertIn("focusLiveDraftTopic", script)
        self.assertIn("left.lastSeen", script)
        self.assertIn(".live-draft-report", workspace_styles)
        self.assertIn(".transcript-line.is-report-focus", workspace_styles)
        self.assertIn('workspace.append(media, raw)', script)
        self.assertIn('stage.append(head, workspace, insights, cinemaExitButton)', script)
        self.assertIn('raw.classList.add("is-side")', script)
        self.assertIn('insights.classList.add("is-below")', script)
        self.assertIn("expandPostProcessingBroadcast", script)
        self.assertIn('assemblyTranscriptState.expandedMode = "POST_PROCESSING"', script)
        self.assertIn('const hasReportResult = hasProvisionalResult || hasOfficialResult', script)
        self.assertIn("meetingBriefResultCounts", script)
        self.assertIn("showLiveReportHandoff", script)
        self.assertIn("LIVE_CONTINUITY_WINDOW_MS = 24 * 60 * 60 * 1000", script)
        self.assertIn("broadcastWasActiveWithin24Hours", script)
        self.assertNotIn("continuityEndedCount < 4", script)
        self.assertIn("실시간 초안 전체 보기 · 발언 묶음", script)
        self.assertIn("상위 핵심 주제", script)
        self.assertIn("전체 발언 묶음", script)
        self.assertIn("live_topic_lineage", script)
        self.assertIn("meeting-lineage-unmapped", script)
        self.assertIn("실시간 주제 계보", script)
        self.assertIn(".meeting-topic-lineage", workspace_styles)
        self.assertIn("expandPostProcessingBroadcast(ended, processingRow)", script)
        self.assertIn(".live-report-handoff", workspace_styles)
        self.assertIn('"meeting-topic-task-overview-list"', script)
        self.assertIn("const MEETING_OVERVIEW_VISIBLE_ROWS = 5;", script)
        self.assertIn(
            "limitMeetingOverviewRows(topicTaskOverviewList, MEETING_OVERVIEW_VISIBLE_ROWS)",
            script,
        )
        self.assertIn('list.dataset.visibleRows = String(visibleCount)', script)
        self.assertNotIn("rows.slice(0, visibleCount).reduce", script)
        self.assertIn("linkedTasks.slice(0, 1)", script)
        self.assertIn("for (const task of unlinkedTasks)", script)
        self.assertIn("meetingTaskOwnerTags(task)", script)
        self.assertIn(".meeting-topic-task-overview-list.is-scrollable", workspace_styles)
        self.assertIn("max-height:360px; overflow-y:scroll", workspace_styles)
        self.assertIn("height:72px; min-height:72px", workspace_styles)
        self.assertIn(".meeting-task-owner-tags", workspace_styles)
        self.assertIn('activateWorkspaceTab("reports")', script)
        self.assertIn(".raw-transcript.is-side", workspace_styles)
        self.assertIn(".live-insights.is-compact.is-below", workspace_styles)
        self.assertIn('"live-draft-overview-list"', script)
        self.assertIn(".live-draft-overview-list { max-height:290px", workspace_styles)
        self.assertIn("overflow-y: scroll", workspace_styles)
        self.assertIn(".transcript-stage.is-cinema > .live-insights.is-below { display:block; }", workspace_styles)
        self.assertIn(".transcript-stage.is-cinema .live-workspace > .raw-transcript.is-side { display:none!important", workspace_styles)
        self.assertIn("transcript-scroll-controls", script)
        self.assertIn("transcript-scroll-range", script)
        self.assertIn("updateTranscriptScrollRange", script)
        self.assertIn('document.createElement(reviewMode ? "details" : "section")', script)
        self.assertIn('container.querySelector(":scope > .live-insight-empty")?.remove()', script)
        self.assertIn("grid-template-rows:auto minmax(0,1fr) auto", workspace_styles)
        self.assertIn("scrollTranscriptToLatest", script)
        self.assertIn("liveReportFilterState", script)
        self.assertIn("if (assemblyTranscriptState.broadcastId)", script)
        self.assertIn("} else if (assemblyTranscriptState.committee)", script)
        self.assertIn('document.activeElement !== filterInput', script)
        self.assertIn('filterBar.parentElement !== report', script)
        self.assertIn('report.parentElement !== container', script)
        self.assertNotIn('const next = container.querySelector(".live-report-filter input")', script)
        self.assertIn("openLiveDraftEvidenceDialog", script)
        self.assertIn('id="liveDraftEvidenceDialog"', html)
        self.assertIn("live-report-filter", workspace_styles)
        self.assertIn('addMeetingRailCard(liveContainer', script)
        self.assertIn('addMeetingRailCard(reportContainer', script)
        self.assertIn('document.querySelector(liveMode ? "#liveOperationsExpandedStage"', script)
        self.assertIn("renderWatchTestLive", script)
        self.assertIn('liveItem?.status === "COMPLETED"', script)
        self.assertIn('"생방송 없음"', script)
        self.assertIn('watchTestLiveState?.status === "COMPLETED"', script)
        self.assertIn('document.addEventListener("watch-test-live-update"', script)
        self.assertIn('panel?.classList.contains("is-embedded")', watch_script)
        self.assertIn("mount.append(panel)", watch_script)
        self.assertIn('new CustomEvent("watch-test-live-update"', watch_script)
        self.assertIn('const RULES_KEY = "poc07.watch.rules.v1"', watch_script)
        self.assertIn("synchronizeLocalRules", watch_script)
        self.assertIn("saveLocalRules", watch_script)
        self.assertIn("NOTIFICATION_LIMIT = 12", watch_script)
        self.assertIn('method: "DELETE"', watch_script)
        self.assertIn('id="watchRuleComposer"', html)
        self.assertIn('id="watchClearRead"', html)
        self.assertIn('id="watchRuleDigest"', html)
        self.assertIn('id="watchRuleKakao"', html)
        self.assertIn('id="watchKakaoAction"', html)
        self.assertIn('id="watchOperatorPanel"', html)
        self.assertIn('id="watchIntegratedSummary"', html)
        self.assertIn('value="FIRST_PER_SPEAKER"', html)
        self.assertIn('value="INTERVAL_60_MINUTES"', html)
        self.assertIn('id="watchMetrics"', html)
        self.assertIn('id="watchRuleReportDialog"', html)
        self.assertIn("loadMetrics", watch_script)
        self.assertIn("openRuleReport", watch_script)
        self.assertIn("downloadRuleReport", watch_script)
        self.assertIn("printRuleReport", watch_script)
        self.assertIn("notification.notification_type === \"DIGEST\"", watch_script)
        self.assertIn('"meeting-report-tools"', script)
        self.assertIn("brief.md", script)
        self.assertIn("meeting-report-print-mode", workspace_styles)
        self.assertIn(".watch-rule-composer", styles)
        self.assertIn(".watch-notification-row", styles)
        self.assertIn(".watch-alert-panel.is-embedded", styles)
        self.assertNotIn('id="watchAlertButton"', html)
        self.assertNotIn('id="watchTestStage"', html)
        self.assertNotIn(".watch-test-stage", styles)

    def test_live_count_and_unread_alert_badge_are_not_conflated(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        script = (PROJECT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        watch_script = (PROJECT_DIR / "web" / "watch-alerts.js").read_text(encoding="utf-8")
        styles = (PROJECT_DIR / "web" / "workspace.css").read_text(encoding="utf-8")

        self.assertIn('aria-label="읽지 않은 알림 0건">새 알림 0</em>', html)
        self.assertIn('`새 알림 ${Math.min(state.unread, 99)}`', watch_script)
        self.assertIn('`생방송 ${liveCount}건`', script)
        self.assertIn("mergeOfficialLiveBroadcasts(payload, activeTranscript)", script)
        self.assertIn("item.broadcast_id = match.broadcast_id", script)
        self.assertIn("min-width:38px", styles)

    def test_dashboard_assets_and_mount_points_are_present(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        for marker in (
            'id="meetingMetric"',
            'id="committeeMeetingList"',
            'id="billExplorer"',
            'src="assets/dashboard.js?v=',
            'href="assets/dashboard.css?v=',
        ):
            self.assertIn(marker, html)

    def test_workspace_makes_recording_continuity_and_readability_explicit(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        script = (PROJECT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        styles = (PROJECT_DIR / "web" / "workspace.css").read_text(encoding="utf-8")
        for marker in (
            'href="assets/workspace.css?v=',
            'id="topTabLive"',
            "정부 정책 브리핑",
            "정부와 국회, 같은 주제에서 보기",
            "위원회 논의와 의안 결과",
        ):
            self.assertIn(marker, html)
        self.assertIn('data-workspace-tab="live"', html)
        self.assertNotIn('data-workspace-tab="cabinet"', html)
        self.assertNotIn('data-workspace-tab="assembly"', html)
        for panel in ("live", "cabinet", "assembly"):
            self.assertIn(f'data-workspace-panel="{panel}"', html)
        self.assertIn("activateWorkspaceTab", script)
        self.assertIn("selectInitialWorkspaceForLiveStatus(anyLive)", script)
        self.assertIn('const target = anyLive ? "live" : "reports"', script)
        self.assertIn("initialWorkspaceAutoSelectionPending = false", script)
        self.assertIn('event.key === "ArrowRight"', script)
        self.assertIn('role="tablist"', html)
        self.assertIn('role="tabpanel"', html)
        self.assertNotIn("hero-panel compact-title", html)
        self.assertNotIn("workspace-tabs", html)
        self.assertIn('liveNavTab?.classList.toggle("has-live", anyLive)', script)
        self.assertIn("처음부터 현재까지 · 자동 갱신", script)
        self.assertIn("처음부터 끝까지 · 공식본 대조", script)
        self.assertIn("font-size: 16px", styles)
        self.assertIn("aspect-ratio: 16 / 9", styles)
        self.assertIn("dark only for media", styles)

    def test_dashboard_uses_only_public_api_routes(self):
        script = (PROJECT_DIR / "web" / "dashboard.js").read_text(encoding="utf-8")
        self.assertIn('api/committees/meetings', script)
        self.assertIn('api/bills?', script)
        self.assertNotIn("NATIONAL_ASSEMBLY_API_KEY", script)
        self.assertNotIn("DATABASE_URL", script)


    def test_live_flow_and_official_vote_summary_are_exposed(self):
        schedule_script = (PROJECT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        dashboard_script = (PROJECT_DIR / "web" / "dashboard.js").read_text(encoding="utf-8")
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        votes = json.loads(
            (PROJECT_DIR / "web" / "data" / "vote_summaries.json").read_text(encoding="utf-8")
        )
        self.assertNotIn("department-scope-change", schedule_script)
        self.assertIn("loadOfficialRotations", schedule_script)
        self.assertIn('getJson("api/live/status"', schedule_script)
        self.assertIn("renderDetectedAssemblyLive", schedule_script)
        self.assertIn("api/live/transcript/snapshot?", schedule_script)
        self.assertIn("api/live/transcript/delta?", schedule_script)
        self.assertIn("assemblyTranscriptState.cursor", schedule_script)
        self.assertIn("buildLiveTopics", schedule_script)
        self.assertIn("item.live_insight", schedule_script)
        self.assertIn("similarLiveTopic", schedule_script)
        self.assertIn("score >= 0.6", schedule_script)
        self.assertIn("liveTopicOverlap", schedule_script)
        self.assertIn("contextualMatch", schedule_script)
        self.assertIn("group.topicTokens.add", schedule_script)
        self.assertIn("new Set(groups.values())", schedule_script)
        self.assertIn('topic_id: `ai:${topicKey || insight.topic}`', schedule_script)
        self.assertNotIn("const liveTopicRules", schedule_script)
        self.assertIn("미해결 후속 과제", schedule_script)
        self.assertIn('task_status === "OPEN"', schedule_script)
        self.assertIn('"status": "PROVISIONAL"', (
            PROJECT_DIR / "backend" / "app" / "services" / "summary_contract.py"
        ).read_text(encoding="utf-8"))
        self.assertIn("liveItem?.stream_url", schedule_script)
        self.assertNotIn("OFFICIAL HLS STREAM", schedule_script)
        self.assertIn("api/live/broadcasts?", schedule_script)
        self.assertIn("/transcript`, { cache", schedule_script)
        self.assertIn("LAST LIVE REVIEW", schedule_script)
        self.assertIn("renderBroadcastRows", schedule_script)
        self.assertIn("const MEETING_HISTORY_INITIAL_LIMIT = 5", schedule_script)
        self.assertIn("const MEETING_HISTORY_PAGE_SIZE = 5", schedule_script)
        self.assertIn("loadMoreMeetingHistory", schedule_script)
        self.assertIn("meetingRailNearLoadedEnd", schedule_script)
        self.assertIn("preservedScrollLeft", schedule_script)
        self.assertIn("offset: String(meetingRailHistoryState.nextOffset)", schedule_script)
        self.assertIn("for (const ended of historyPayload.items || [])", schedule_script)
        self.assertIn("`시작 ${startedAt.toLocaleString", schedule_script)
        self.assertIn("expandLiveBroadcast", schedule_script)
        self.assertIn("expandEndedBroadcast", schedule_script)
        self.assertIn("renderOfficialContext", schedule_script)
        self.assertIn("LIVE 저장본 · PROVISIONAL", schedule_script)
        self.assertIn("공식 회의록 원문", schedule_script)
        self.assertIn("live-utterance-list", schedule_script)
        self.assertIn("renderCompactLiveInsights", schedule_script)
        self.assertIn("시네마 모드", schedule_script)
        self.assertNotIn("assemblyCaptionOverlay", schedule_script)
        self.assertIn("word-break: keep-all", (PROJECT_DIR / "web" / "styles.css").read_text(encoding="utf-8"))
        self.assertIn("@container (max-width: 900px)", (PROJECT_DIR / "web" / "styles.css").read_text(encoding="utf-8"))
        self.assertIn("liveInsightFilterState", schedule_script)
        self.assertNotIn('id="followUpTasks"', html)
        self.assertNotIn('id="followUpMinistry"', html)
        self.assertIn('id="meetingRailPrev"', html)
        self.assertIn('id="meetingRailNext"', html)
        self.assertNotIn('id="departmentScope"', html)
        self.assertNotIn("관심 분야", html)
        self.assertNotIn("회의 흐름", html)
        self.assertIn('id="aiUsage"', html)
        self.assertIn('id="aiOpenRouterAmount"', html)
        self.assertIn('id="aiOpenRouterReset"', html)
        self.assertIn('id="aiMistralAmount"', html)
        self.assertIn('id="aiMistralReset"', html)
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr))", (
            PROJECT_DIR / "web" / "workspace.css"
        ).read_text(encoding="utf-8"))
        self.assertIn("setAiUsageMeter", schedule_script)
        self.assertIn('id="todayScheduleBoard"', html)
        self.assertIn('id="todaySchedulePrev"', html)
        self.assertIn('id="todayScheduleNext"', html)
        self.assertIn('getJson("api/schedule/today"', schedule_script)
        self.assertIn("renderTodayScheduleBoard", schedule_script)
        self.assertIn("const TODAY_SCHEDULE_HOLD_MS = 5000", schedule_script)
        self.assertIn("const TODAY_SCHEDULE_TRANSITION_MS = 2000", schedule_script)
        self.assertIn("window.setTimeout(() => {", schedule_script)
        self.assertNotIn('state: "scheduled"', schedule_script)
        self.assertIn('fetch("api/ai/usage"', schedule_script)
        self.assertIn("scrollMeetingRailByOneCard", schedule_script)
        self.assertIn("card.getBoundingClientRect().width + gap", schedule_script)
        self.assertNotIn("rail.clientWidth * 0.8", schedule_script)
        self.assertIn("addMeetingRailCard", schedule_script)
        self.assertIn("meeting-card-tags", schedule_script)
        self.assertIn("meeting-card-meta", schedule_script)
        self.assertIn('{ label: "진행중", tone: "active" }', schedule_script)
        self.assertIn('{ label: "기록 중", tone: "recording" }', schedule_script)
        self.assertIn('{ label: "완료", tone: "complete" }', schedule_script)
        self.assertIn('{ label: "비공식 정리", tone: "provisional" }', schedule_script)
        self.assertIn('{ label: "공식정리", tone: "official" }', schedule_script)
        workspace = (PROJECT_DIR / "web" / "workspace.css").read_text(encoding="utf-8")
        self.assertIn('.meeting-card-tag.is-active', workspace)
        self.assertIn('.meeting-card-tag.is-recording', workspace)
        self.assertIn('background: #fff0f1', workspace)
        self.assertIn('background: #fff7d6', workspace)
        self.assertIn("flex: 0 0 calc((100% - 30px) / 4)", workspace)
        self.assertIn("height: 120px", workspace)
        self.assertIn(".meeting-rail::-webkit-scrollbar { height: 5px; }", workspace)
        self.assertIn("scrollbar-color: #123f78 #dbe7f6", workspace)
        self.assertIn("expandExecutiveBriefing", schedule_script)
        self.assertNotIn('magazineElement("section", "government-source-flow"', schedule_script)
        self.assertNotIn("공식 자료 연결", schedule_script)
        self.assertNotIn("대통령실 대변인 브리핑", schedule_script)
        self.assertNotIn("국무회의 공식 부처보고", schedule_script)
        self.assertNotIn("공식 심의 안건 소관", schedule_script)
        self.assertNotIn("연결된 부처 공식 브리핑", schedule_script)
        self.assertIn("presidential-guidance", schedule_script)
        self.assertIn(
            ".executive-agenda-view article.presidential-guidance.standalone > p",
            workspace,
        )
        self.assertIn("presidential-directive-line", schedule_script)
        self.assertIn("guidance.display_text || guidance.text", schedule_script)
        self.assertIn("공식자료만 반영 · 상세내용 미공개", schedule_script)
        self.assertIn("공식 발언 ${paragraphs.length}개 보기", schedule_script)
        self.assertIn("guidance.topic || \"국정 현안 후속조치\"", schedule_script)
        self.assertIn(".presidential-directive-owner", workspace)
        assembly_extras = (PROJECT_DIR / "web" / "assembly-extras.css").read_text(
            encoding="utf-8",
        )
        self.assertIn("align-items:stretch", assembly_extras)
        self.assertIn("grid-template-rows:auto minmax(0,1fr)", assembly_extras)
        topic_report_styles = (PROJECT_DIR / "web" / "topic-reports.css").read_text(
            encoding="utf-8",
        )
        self.assertIn("height: auto", topic_report_styles)
        self.assertIn("min-height: 300px", topic_report_styles)
        self.assertIn("height:44px", topic_report_styles)
        self.assertIn("대통령 지시", schedule_script)
        self.assertIn("부처 보고 내용", schedule_script)
        self.assertIn('magazineElement("span", "", "부처 추가 발표")', schedule_script)
        self.assertIn("briefing.display_summary", schedule_script)
        self.assertNotIn('magazineElement("p", "", briefing.summary)', schedule_script)
        self.assertIn('magazineElement("a", "", "원문 확인 ↗")', schedule_script)
        self.assertIn(
            ".executive-agenda-view article .presidential-directive-line > span",
            workspace,
        )
        self.assertIn("const parts = text.match", schedule_script)
        self.assertIn(
            'key: "ministry_reports", label: "부처 보고 내용"', schedule_script,
        )
        self.assertNotIn('key: "spokesperson_briefing", label: "대변인 브리핑"', schedule_script)
        self.assertIn('key: "deliberated_agendas", label: "심의안건"', schedule_script)
        self.assertIn("executiveOfficialMatchKey", schedule_script)
        self.assertIn('"MEETING_NUMBER_AND_DATE"', schedule_script)
        self.assertIn('timeZone: "Asia/Seoul"', schedule_script)
        self.assertIn("LIVE 감지 기록 연결됨 · 자막 저장 전 감지", schedule_script)
        self.assertNotIn('{ label: "LIVE 감지", tone: "provisional" }', schedule_script)
        self.assertNotIn('status: "공식 정리", institution: "대통령실"', schedule_script)
        self.assertNotIn('id: "presidential-"', schedule_script)
        self.assertIn("국회·정부 정책 통합 흐름", html)
        self.assertIn("정부 회의·공식 발표", html)
        self.assertIn("expandEndedExecutiveBroadcast", schedule_script)
        self.assertIn("executiveMeetingNumber", schedule_script)
        self.assertNotIn("공식 자료 대기", schedule_script)
        self.assertIn("live_capture", schedule_script)
        self.assertIn("/brief/official", schedule_script)
        self.assertIn("renderOfficialBriefIntegration", schedule_script)
        self.assertIn("LIVE 분석 ↔ 공식 회의록", schedule_script)
        self.assertIn("관련 공식 발언", schedule_script)
        self.assertIn("공식 정책 발언", schedule_script)
        self.assertIn("공식 승인이나 과제 확정을 뜻하지 않습니다", schedule_script)
        self.assertIn("renderFollowUpTasks", schedule_script)
        self.assertIn("openTaskBroadcast", schedule_script)
        self.assertIn("officialReconciliation", schedule_script)
        self.assertIn("공식본 일치", schedule_script)
        self.assertIn("공식본 미확인", schedule_script)
        self.assertIn("대조된 공식 발언 보기", schedule_script)
        self.assertIn('id="liveBroadcastRows"', html)
        self.assertIn('id="liveExpanded"', html)
        self.assertNotIn('id="liveReviewDialog"', html)
        self.assertIn("showMagazineCard", schedule_script)
        self.assertIn("AUTO REVIEW", schedule_script)
        self.assertIn("official_published", schedule_script)
        self.assertIn("공식 원문 확인", schedule_script)
        self.assertIn('id="live"', html)
        self.assertIn('id="presidential"', html)
        self.assertIn("renderAssemblyFallback", dashboard_script)
        self.assertIn('id="executiveMagazine"', html)
        self.assertIn('id="assemblyMagazine"', html)
        self.assertIn("votePanel", dashboard_script)
        self.assertIn("committee-row", dashboard_script)
        self.assertIn("bill-row", dashboard_script)
        self.assertIn("inlineVoteText", dashboard_script)
        self.assertIn("bill-hover-detail", dashboard_script)
        self.assertIn("assets/data/vote_summaries.json", dashboard_script)
        self.assertEqual(votes["resource"], "nojepdqqaweusdfbi")
        self.assertEqual(votes["items"][0]["yes"], 215)
        self.assertEqual(votes["items"][0]["no"], 2)
        self.assertNotIn("KEY=", votes["items"][0]["source_url"])

    def test_committee_rows_expose_official_transcript_dialog(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        script = (PROJECT_DIR / "web" / "dashboard.js").read_text(encoding="utf-8")
        styles = (PROJECT_DIR / "web" / "dashboard.css").read_text(encoding="utf-8")
        self.assertIn("officialTranscriptDialog", html)
        self.assertIn("openOfficialTranscript", script)
        self.assertIn("official_utterance_count", script)
        self.assertIn("official-utterance", styles)
        self.assertIn("AUTO CLASSIFICATION · DRAFT", script)
        self.assertIn("payload.insights.topics", script)

    def test_integrated_policy_flow_has_visual_and_evidence_contract(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        script = (PROJECT_DIR / "web" / "dashboard.js").read_text(encoding="utf-8")
        styles = (PROJECT_DIR / "web" / "dashboard.css").read_text(encoding="utf-8")
        self.assertIn('id="committeePolicyFlow"', html)
        self.assertIn("api/committees/policy-flow?", script)
        self.assertIn("policy_statement_count", script)
        self.assertIn("item.evidence.source_span_id", script)
        self.assertIn("payload.linked_bill_count", script)
        self.assertIn("EXACT AGENDA → BILL → VOTE", script)
        self.assertIn("voteSummaries.get(bill.bill_id)", script)
        self.assertIn("policy-signal-bar", styles)
        self.assertIn("policy-bill-flow", styles)

    def test_official_executive_briefings_fill_presidential_flow(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        script = (PROJECT_DIR / "web" / "dashboard.js").read_text(encoding="utf-8")
        live_script = (PROJECT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        styles = (PROJECT_DIR / "web" / "styles.css").read_text(encoding="utf-8")
        self.assertIn('id="executiveLatestMeeting"', html)
        self.assertIn('id="executiveMessageMetric"', html)
        self.assertIn('new URLSearchParams({ limit: "10" })', script)
        self.assertIn('fetch("api/executive/briefings?" + params', script)
        self.assertIn("RULE LINK", script)
        self.assertIn("executive-meeting-list", script)
        self.assertIn("OFFICIAL MESSAGE", script)
        self.assertIn("message.source_span_id", script)
        self.assertIn("executive-policy-row", styles)
        self.assertIn('id="executiveFilterForm"', html)
        self.assertIn("executiveMinistryFilter", script)
        self.assertIn("executive-filter-bar", styles)
        self.assertIn("item.official_document?.sections", script)
        self.assertIn("OFFICIAL PDF TEXT", script)
        self.assertIn("bill-official-text", styles)
        self.assertNotIn("DEMO LIVE · SIMULATION", live_script)
        self.assertNotIn("E2E 데모 LIVE", live_script)
        self.assertNotIn("sim-committee-hearing", live_script)
        self.assertNotIn("demo_live_count", live_script)
        self.assertIn("task.topic_id ? task.topic_id === topic.id", live_script)
        self.assertNotIn("여러 주제에 걸친 과제", live_script)

    def test_cross_institution_flow_exposes_both_official_evidence_sides(self):
        html = (PROJECT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        script = (PROJECT_DIR / "web" / "dashboard.js").read_text(encoding="utf-8")
        styles = (PROJECT_DIR / "web" / "styles.css").read_text(encoding="utf-8")
        self.assertIn('id="crossInstitutionFlow"', html)
        self.assertIn("api/policy/cross-institution-flow?", script)
        self.assertIn("EXECUTIVE · OFFICIAL", script)
        self.assertIn("LEGISLATURE · OFFICIAL TEXT", script)
        self.assertIn("item.shared_evidence_keywords", script)
        self.assertIn("item.temporal_label", script)
        self.assertIn("cross-flow-evidence", styles)
        self.assertIn("cross-flow-rule", styles)

    def test_integrated_brief_evidence_prefers_official_complete_utterances(self):
        api = (PROJECT_DIR / "backend" / "app" / "main.py").read_text(
            encoding="utf-8"
        )
        self.assertIn("live_utterances = [", api)
        self.assertIn("official_utterances = (", api)
        self.assertIn("official_presentations or live_utterances", api)
        self.assertIn('"OFFICIAL_TRANSCRIPT_PRESENTATION"', api)

if __name__ == "__main__":
    unittest.main()
