-- PoC 08 전용 Supabase Data API 스키마.
-- 다른 PoC와 테이블명이 겹치지 않도록 모든 객체에 poc08_ 접두사를 사용한다.

create table if not exists public.poc08_notices (
    id integer generated by default as identity primary key,
    source varchar(30) not null default 'g2b',
    stage varchar(30) not null,
    notice_no varchar(120) not null,
    bid_no varchar(120),
    agency_name varchar(300) not null default '',
    agency_code varchar(100),
    title varchar(1000) not null,
    budget_amount bigint,
    posted_at timestamptz,
    deadline_at timestamptz,
    url text,
    business_type varchar(50) not null default 'service',
    raw_payload_json jsonb not null default '{}'::jsonb,
    collect_status varchar(30) not null default 'collected',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint poc08_uq_notice_source_stage_no unique (source, stage, notice_no)
);

create index if not exists poc08_ix_notice_posted_grade on public.poc08_notices (posted_at, stage);

create table if not exists public.poc08_attachments (
    id integer generated by default as identity primary key,
    notice_id integer not null references public.poc08_notices(id) on delete cascade,
    original_filename varchar(1000) not null default '',
    stored_filename varchar(1000),
    file_path text,
    file_ext varchar(20),
    file_size bigint,
    sha256 varchar(64),
    source_url text not null,
    download_status varchar(30) not null default 'pending',
    download_error text,
    parse_status varchar(30) not null default 'pending',
    parse_error text,
    text_path text,
    text_excerpt text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint poc08_uq_attachment_notice_url unique (notice_id, source_url)
);

create index if not exists poc08_ix_attachment_notice_id on public.poc08_attachments (notice_id);
create index if not exists poc08_ix_attachment_sha256 on public.poc08_attachments (sha256);

create table if not exists public.poc08_analysis_runs (
    id integer generated by default as identity primary key,
    notice_id integer not null references public.poc08_notices(id) on delete cascade,
    run_type varchar(30) not null,
    model_name varchar(300),
    input_hash varchar(64) not null,
    status varchar(30) not null,
    result_json jsonb not null default '{}'::jsonb,
    confidence double precision,
    cost_prompt_tokens integer,
    cost_completion_tokens integer,
    error_message text,
    created_at timestamptz not null default now()
);

create index if not exists poc08_ix_analysis_notice_type on public.poc08_analysis_runs (notice_id, run_type);

create table if not exists public.poc08_notice_decisions (
    id integer generated by default as identity primary key,
    notice_id integer not null unique references public.poc08_notices(id) on delete cascade,
    final_grade varchar(1) not null default 'D',
    ai_relevance varchar(20) not null default 'low',
    common_platform_fit varchar(20) not null default 'uncertain',
    usage_mentioned varchar(20) not null default 'unclear',
    priority_score integer not null default 0,
    recommended_action varchar(30) not null default 'manual_review',
    summary text not null default '자료를 추가 확인해야 합니다.',
    possible_functions_json jsonb not null default '[]'::jsonb,
    key_evidence_json jsonb not null default '[]'::jsonb,
    check_questions_json jsonb not null default '[]'::jsonb,
    caveats_json jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists poc08_ix_decision_grade on public.poc08_notice_decisions (final_grade);
create index if not exists poc08_ix_decision_priority on public.poc08_notice_decisions (priority_score);

create table if not exists public.poc08_action_items (
    id integer generated by default as identity primary key,
    notice_id integer not null unique references public.poc08_notices(id) on delete cascade,
    status varchar(30) not null default 'new',
    owner varchar(200),
    contacted_at timestamptz,
    agency_response text,
    saving_estimate bigint,
    security_effect_note text,
    memo text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists poc08_ix_action_status on public.poc08_action_items (status);

create table if not exists public.poc08_pipeline_runs (
    id integer generated by default as identity primary key,
    run_kind varchar(40) not null,
    mode varchar(30) not null default 'mock',
    status varchar(30) not null default 'running',
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    stats_json jsonb not null default '{}'::jsonb,
    error_message text
);

create index if not exists poc08_ix_pipeline_run_kind on public.poc08_pipeline_runs (run_kind);

create table if not exists public.poc08_audit_logs (
    id integer generated by default as identity primary key,
    event_type varchar(80) not null,
    entity_type varchar(80),
    entity_id varchar(80),
    actor varchar(200) not null default 'system',
    detail_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists poc08_ix_audit_event_type on public.poc08_audit_logs (event_type);

alter table public.poc08_notices enable row level security;
alter table public.poc08_attachments enable row level security;
alter table public.poc08_analysis_runs enable row level security;
alter table public.poc08_notice_decisions enable row level security;
alter table public.poc08_action_items enable row level security;
alter table public.poc08_pipeline_runs enable row level security;
alter table public.poc08_audit_logs enable row level security;

-- 브라우저 클라이언트에는 정책을 만들지 않는다. 서버의 service_role만 접근한다.
revoke all on public.poc08_notices from anon, authenticated;
revoke all on public.poc08_attachments from anon, authenticated;
revoke all on public.poc08_analysis_runs from anon, authenticated;
revoke all on public.poc08_notice_decisions from anon, authenticated;
revoke all on public.poc08_action_items from anon, authenticated;
revoke all on public.poc08_pipeline_runs from anon, authenticated;
revoke all on public.poc08_audit_logs from anon, authenticated;

grant select, insert, update, delete on public.poc08_notices to service_role;
grant select, insert, update, delete on public.poc08_attachments to service_role;
grant select, insert, update, delete on public.poc08_analysis_runs to service_role;
grant select, insert, update, delete on public.poc08_notice_decisions to service_role;
grant select, insert, update, delete on public.poc08_action_items to service_role;
grant select, insert, update, delete on public.poc08_pipeline_runs to service_role;
grant select, insert, update, delete on public.poc08_audit_logs to service_role;

grant usage, select on sequence public.poc08_notices_id_seq to service_role;
grant usage, select on sequence public.poc08_attachments_id_seq to service_role;
grant usage, select on sequence public.poc08_analysis_runs_id_seq to service_role;
grant usage, select on sequence public.poc08_notice_decisions_id_seq to service_role;
grant usage, select on sequence public.poc08_action_items_id_seq to service_role;
grant usage, select on sequence public.poc08_pipeline_runs_id_seq to service_role;
grant usage, select on sequence public.poc08_audit_logs_id_seq to service_role;
