/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksTaskIdIndexRouteImport } from './routes/tasks.$taskId.index'
import { Route as TasksTaskIdNewRouteImport } from './routes/tasks.$taskId.new'
import { Route as TasksTaskIdResultIdRouteImport } from './routes/tasks.$taskId.$resultId'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdIndexRoute = TasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdNewRoute = TasksTaskIdNewRouteImport.update({
  id: '/tasks/$taskId/new',
  path: '/tasks/$taskId/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdResultIdRoute = TasksTaskIdResultIdRouteImport.update({
  id: '/tasks/$taskId/$resultId',
  path: '/tasks/$taskId/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/statistics': typeof StatisticsRoute
  '/tasks/$taskId/$resultId': typeof TasksTaskIdResultIdRoute
  '/tasks/$taskId/new': typeof TasksTaskIdNewRoute
  '/tasks/$taskId/': typeof TasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/statistics': typeof StatisticsRoute
  '/tasks/$taskId/$resultId': typeof TasksTaskIdResultIdRoute
  '/tasks/$taskId/new': typeof TasksTaskIdNewRoute
  '/tasks/$taskId': typeof TasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/statistics': typeof StatisticsRoute
  '/tasks/$taskId/$resultId': typeof TasksTaskIdResultIdRoute
  '/tasks/$taskId/new': typeof TasksTaskIdNewRoute
  '/tasks/$taskId/': typeof TasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/statistics'
    | '/tasks/$taskId/$resultId'
    | '/tasks/$taskId/new'
    | '/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/statistics'
    | '/tasks/$taskId/$resultId'
    | '/tasks/$taskId/new'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/statistics'
    | '/tasks/$taskId/$resultId'
    | '/tasks/$taskId/new'
    | '/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  StatisticsRoute: typeof StatisticsRoute
  TasksTaskIdResultIdRoute: typeof TasksTaskIdResultIdRoute
  TasksTaskIdNewRoute: typeof TasksTaskIdNewRoute
  TasksTaskIdIndexRoute: typeof TasksTaskIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/': {
      id: '/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof TasksTaskIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/new': {
      id: '/tasks/$taskId/new'
      path: '/tasks/$taskId/new'
      fullPath: '/tasks/$taskId/new'
      preLoaderRoute: typeof TasksTaskIdNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/$resultId': {
      id: '/tasks/$taskId/$resultId'
      path: '/tasks/$taskId/$resultId'
      fullPath: '/tasks/$taskId/$resultId'
      preLoaderRoute: typeof TasksTaskIdResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  StatisticsRoute: StatisticsRoute,
  TasksTaskIdResultIdRoute: TasksTaskIdResultIdRoute,
  TasksTaskIdNewRoute: TasksTaskIdNewRoute,
  TasksTaskIdIndexRoute: TasksTaskIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
