"""Firefox smoke test for AIWorks editor usability.

Run from the repository root:
    .venv/bin/python PoC/06-AIWorks/tests/browser_smoke.py
"""

from __future__ import annotations

import json
import os
import tempfile
import time
import zipfile
from xml.etree import ElementTree as ET
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import TimeoutException


URL = os.getenv("AIWORKS_BROWSER_URL", "http://127.0.0.1:8000/poc/aiworks/")
GECKODRIVER = os.getenv("AIWORKS_GECKODRIVER", "/snap/bin/geckodriver")


def wait_for(driver, expression: str, timeout: int = 10):
    return WebDriverWait(driver, timeout).until(
        lambda current: current.execute_script(f"return Boolean({expression})")
    )


def scroll_metrics(driver, selector: str) -> dict:
    return driver.execute_script(
        """
        const node = document.querySelector(arguments[0]);
        return {
          clientHeight: node.clientHeight,
          scrollHeight: node.scrollHeight,
          overflowY: getComputedStyle(node).overflowY
        };
        """,
        selector,
    )

def approve_live_rewrite(driver) -> dict:
    wait_for(driver, "document.querySelector('#approvalDialog').open")
    external_transfer = driver.find_element(By.ID, "externalTransfer")
    if not external_transfer.is_enabled():
        raise AssertionError("selection rewrite did not request external-transfer approval")
    external_transfer.click()
    driver.find_element(By.ID, "approveRun").click()
    wait_for(driver, "!document.querySelector('#proposal').hidden", timeout=60)
    proposal = driver.execute_script(
        "return {before:document.querySelector('#proposal').dataset.before,"
        "after:document.querySelector('#proposal').dataset.after,"
        "label:document.querySelector('#proposalIntent').textContent}"
    )
    if proposal["after"].strip() == proposal["before"].strip():
        raise AssertionError(f"live LLM copied the source text: {proposal}")
    if not proposal["label"].startswith("실제 LLM"):
        raise AssertionError(f"selection rewrite was not generated by a live model: {proposal}")
    return proposal


def main() -> None:
    if not Path(GECKODRIVER).exists():
        raise SystemExit(f"geckodriver not found: {GECKODRIVER}")
    options = Options()
    options.add_argument("-headless")
    with tempfile.TemporaryDirectory(prefix=".aiworks-browser-", dir=Path.cwd()) as temp_name:
        temp_dir = Path(temp_name)
        hwpx_path = temp_dir / "browser-sample.hwpx"
        native_hwpx_path = temp_dir / "native-selection.hwpx"
        markdown_path = temp_dir / "browser-plan.md"
        markdown_path.write_text("# 사업계획\n\n이 문서는 검토가 필요하다.", encoding="utf-8")
        native_fixture = Path("PoC/06-AIWorks/web/rhwp/samples/form-002.hwpx")
        with zipfile.ZipFile(native_fixture) as source, zipfile.ZipFile(
            native_hwpx_path, "w"
        ) as archive:
            for info in source.infolist():
                data = source.read(info.filename)
                if info.filename == "Contents/section0.xml":
                    marker = b'<hp:run charPrIDRef="88"><hp:tbl'
                    inserted = (
                        '<hp:run charPrIDRef="9"><hp:t>검토가 필요하다.</hp:t></hp:run>'.encode()
                        + marker
                    )
                    data = data.replace(marker, inserted, 1)
                archive.writestr(info, data)
        with zipfile.ZipFile(native_fixture) as source, zipfile.ZipFile(
            hwpx_path, "w"
        ) as archive:
            for info in source.infolist():
                data = source.read(info.filename)
                if info.filename == "Contents/section0.xml":
                    marker = b'<hp:run charPrIDRef="88"><hp:tbl'
                    inserted = (
                        '<hp:run charPrIDRef="9"><hp:t>브라우저 HWPX 직접 편집 원문</hp:t></hp:run></hp:p>'
                        '<hp:p id="4000000001" paraPrIDRef="21" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="9"><hp:t>두 번째 HWPX 원문</hp:t></hp:run></hp:p>'
                        '<hp:p id="4000000002" paraPrIDRef="21" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="88"><hp:tbl'
                    ).encode()
                    data = data.replace(marker, inserted, 1)
                archive.writestr(info, data)
        options.set_preference("browser.download.folderList", 2)
        options.set_preference("browser.download.dir", str(temp_dir))
        options.set_preference("browser.download.useDownloadDir", True)
        options.set_preference(
            "browser.helperApps.neverAsk.saveToDisk",
            "application/hwp+zip,application/octet-stream",
        )
        driver = webdriver.Firefox(options=options, service=Service(GECKODRIVER))
        report = {}
        try:
            driver.set_window_size(1440, 900)
            driver.get(URL)
            wait_for(driver, "document.readyState === 'complete'")
            wait_for(
                driver,
                "document.querySelector('.local-badge').textContent.includes('v0.17.0')",
            )
            if not driver.find_element(By.ID, "welcomeScreen").is_displayed():
                raise AssertionError("prompt-first welcome screen is not visible")
            report["promptFirst"] = driver.find_element(By.ID, "welcomeTitle").text
            driver.find_element(By.ID, "enterDemo").click()
            wait_for(driver, "!document.querySelector('#workbench').hidden")

            paragraph = driver.find_element(By.ID, "targetParagraph")
            report["contentEditable"] = (
                paragraph.get_attribute("contenteditable") == "true"
            )
            if not report["contentEditable"]:
                raise AssertionError("target paragraph is not contenteditable")

            editor_scroll = scroll_metrics(driver, ".document-stage")
            report["editorScroll"] = editor_scroll
            if editor_scroll["scrollHeight"] <= editor_scroll["clientHeight"]:
                raise AssertionError(f"editor has no scroll range: {editor_scroll}")
            driver.execute_script(
                "const n=document.querySelector('.document-stage');n.scrollTop=n.scrollHeight"
            )
            report["editorScrollTop"] = driver.execute_script(
                "return document.querySelector('.document-stage').scrollTop"
            )
            if report["editorScrollTop"] <= 0:
                raise AssertionError("editor scrollTop did not move")

            original = paragraph.text
            edited = original + " 직접 편집 확인."
            driver.execute_script(
                "arguments[0].focus();arguments[0].textContent=arguments[1];"
                "arguments[0].dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:' 확인'}));",
                paragraph,
                edited,
            )
            wait_for(
                driver,
                "document.querySelector('#documentSaveState').textContent.includes('저장 필요')",
            )
            driver.execute_script(
                "const n=arguments[0],r=document.createRange(),s=getSelection();"
                "r.selectNodeContents(n);s.removeAllRanges();s.addRange(r);",
                paragraph,
            )
            driver.find_element(By.ID, "formatBold").click()
            wait_for(driver, "document.querySelector('#targetParagraph b') !== null")
            wait_for(driver, "document.querySelector('#liveDocumentPreview b') !== null")
            report["formatAndPreview"] = True
            driver.find_element(By.ID, "saveDocument").click()
            wait_for(
                driver,
                "document.querySelector('#documentSaveState').textContent.includes('저장됨')",
            )
            report["savedText"] = paragraph.text
            if report["savedText"] != edited:
                raise AssertionError(f"edited paragraph was not preserved on save: {report['savedText']!r} != {edited!r}")
            wait_for(driver, "document.querySelector('[data-workspace-document]') !== null")
            workspace_id = driver.find_element(
                By.CSS_SELECTOR, "[data-workspace-document]"
            ).get_attribute("data-workspace-document")
            report["workspaceDocumentId"] = workspace_id

            driver.execute_script(
                "arguments[0].focus();arguments[0].textContent=arguments[1];"
                "arguments[0].dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:' 되돌림'}));",
                paragraph,
                edited + " 되돌림 대상.",
            )
            driver.find_element(By.ID, "undoDirectEdit").click()
            report["undoText"] = paragraph.text
            if report["undoText"] != edited:
                raise AssertionError("direct edit undo did not restore the saved text")

            driver.find_element(
                By.CSS_SELECTOR, ".activitybar [data-view='data']"
            ).click()
            driver.find_element(
                By.CSS_SELECTOR, ".activitybar [data-view='editor']"
            ).click()
            wait_for(
                driver,
                f"document.querySelector('[data-workspace-document=\"{workspace_id}\"]') !== null",
            )
            workspace_button = driver.find_element(
                By.CSS_SELECTOR,
                f'[data-workspace-document="{workspace_id}"]',
            )
            driver.execute_script("arguments[0].click()", workspace_button)
            wait_for(
                driver,
                f"document.querySelector('#targetParagraph').textContent === {json.dumps(edited)}",
            )
            if driver.find_element(By.CSS_SELECTOR, "#targetParagraph b").text != edited:
                raise AssertionError("saved rich text was not restored from the server")
            report["workspaceReopened"] = True

            driver.find_element(By.ID, "hwpxFile").send_keys(str(native_hwpx_path))
            try:
                wait_for(driver, "document.querySelector('#rhwpEditorHost iframe') !== null")
                wait_for(
                    driver,
                    "document.querySelector('#rhwpEditorHost')?.dataset.ready === 'true'",
                    timeout=20,
                )
            except TimeoutException as error:
                diagnostics = driver.execute_script(
                    "return {status:document.querySelector('#statusText').textContent,"
                    "paper:document.querySelector('#documentPaper').textContent.slice(0,500),"
                    "chat:document.querySelector('#chat').textContent.slice(-800)}"
                )
                frames = driver.find_elements(By.CSS_SELECTOR, "#rhwpEditorHost iframe")
                if frames:
                    driver.switch_to.frame(frames[0])
                    diagnostics["iframe"] = driver.execute_script(
                        "return {readyState:document.readyState,"
                        "message:document.querySelector('#sb-message')?.textContent,"
                        "body:document.body.textContent.slice(-500)}"
                    )
                    driver.switch_to.default_content()
                raise AssertionError(f"RHWP editor did not become ready: {diagnostics}") from error
            compact_layout = driver.execute_script(
                "return {titlebar:getComputedStyle(document.querySelector('.titlebar')).display,"
                "plugin:getComputedStyle(document.querySelector('#editorPluginBar')).display,"
                "tabs:getComputedStyle(document.querySelector('.editor-tabs')).display,"
                "menu:getComputedStyle(document.querySelector('#hwpMenuBar')).display,"
                "toolbar:document.querySelector('.document-toolbar').getBoundingClientRect().height,"
                "stagePadding:parseFloat(getComputedStyle(document.querySelector('.document-stage')).paddingTop)}"
            )
            report["rhwpCompactLayout"] = compact_layout
            if compact_layout != {
                "titlebar": "none",
                "plugin": "none",
                "tabs": "none",
                "menu": "none",
                "toolbar": 34,
                "stagePadding": 0,
            }:
                raise AssertionError(f"RHWP compact layout mismatch: {compact_layout}")
            compact_controls = driver.execute_script(
                "return {title:document.querySelector('#nativeCompactTitle')?.textContent,"
                "toggleParent:document.querySelector('#aiSelectionMode')?.parentElement?.className}"
            )
            if compact_controls != {
                "title": "native-selection.hwpx",
                "toggleParent": "document-state",
            }:
                raise AssertionError(f"RHWP compact controls mismatch: {compact_controls}")
            editor_frame = driver.find_element(By.CSS_SELECTOR, "#rhwpEditorHost iframe")
            driver.switch_to.frame(editor_frame)
            wait_for(
                driver,
                "document.querySelector('textarea[aria-label=\"문서 편집 입력\"]') !== null",
                timeout=20,
            )
            driver.execute_script(
                "window.__aiworksEmbedMarker='retain-page-v1';document.querySelector('textarea[aria-label=\"문서 편집 입력\"]').focus()"
            )
            ActionChains(driver).key_down(Keys.CONTROL).send_keys("a").key_up(
                Keys.CONTROL
            ).perform()
            driver.switch_to.default_content()
            driver.find_element(By.ID, "chatInput").click()
            try:
                wait_for(
                    driver,
                    "document.querySelector('#contextSelection').textContent.includes('검토가 필요하다')",
                )
            except TimeoutException as error:
                context_text = driver.find_element(By.ID, "contextSelection").text
                raise AssertionError(
                    f"RHWP selection was not captured: {context_text!r}"
                ) from error
            driver.find_element(By.ID, "chatInput").send_keys(
                "선택한 글귀를 보다 공손한 어투로 바꿔줘"
            )
            driver.find_element(By.CSS_SELECTOR, "#chatForm .send-button").click()
            wait_for(driver, "document.querySelector('#approvalDialog').open")
            external_transfer = driver.find_element(By.ID, "externalTransfer")
            if not external_transfer.is_enabled():
                raise AssertionError("RHWP LLM rewrite did not request external-transfer approval")
            external_transfer.click()
            driver.find_element(By.ID, "approveRun").click()
            wait_for(driver, "!document.querySelector('#proposal').hidden", timeout=60)
            live_proposal = driver.execute_script(
                "return {before:document.querySelector('#proposal').dataset.before,"
                "after:document.querySelector('#proposal').dataset.after,"
                "label:document.querySelector('#proposalIntent').textContent}"
            )
            if live_proposal["after"].strip() == live_proposal["before"].strip():
                raise AssertionError(f"live LLM copied the source text: {live_proposal}")
            if not live_proposal["label"].startswith("실제 LLM"):
                raise AssertionError(f"RHWP rewrite was not generated by a live model: {live_proposal}")
            report["rhwpLiveModel"] = live_proposal["label"]
            driver.find_element(By.ID, "applyProposal").click()
            wait_for(
                driver,
                "document.querySelector('#documentSaveState').textContent.includes('r2')",
                timeout=20,
            )
            retained_frame = driver.find_element(By.CSS_SELECTOR, "#rhwpEditorHost iframe")
            driver.switch_to.frame(retained_frame)
            embed_marker = driver.execute_script("return window.__aiworksEmbedMarker")
            driver.switch_to.default_content()
            if embed_marker != "retain-page-v1":
                raise AssertionError("RHWP iframe was reloaded after applying the LLM suggestion")
            report["rhwpViewportRetained"] = True
            driver.find_element(By.ID, "exportButton").click()
            native_download = temp_dir / "native-selection_AIWorks.hwpx"
            deadline = time.time() + 15
            while time.time() < deadline and not native_download.exists():
                time.sleep(0.2)
            if not native_download.exists():
                diagnostics = driver.execute_script(
                    "return {status:document.querySelector('#statusText').textContent,"
                    "save:document.querySelector('#documentSaveState').textContent,"
                    "toast:document.querySelector('#toast').textContent,"
                    "chat:document.querySelector('#chat').textContent.slice(-500)}"
                )
                diagnostics["files"] = sorted(path.name for path in temp_dir.iterdir())
                raise AssertionError(f"native RHWP selection edit download was not created: {diagnostics}")
            with zipfile.ZipFile(native_download) as downloaded:
                native_section = downloaded.read("Contents/section0.xml").decode()
                native_text = "".join(ET.fromstring(native_section).itertext())
                if live_proposal["after"] not in native_text:
                    raise AssertionError(f"live LLM replacement was not saved: {live_proposal}")
            report["rhwpNativeSelectionEdit"] = True
            native_download.unlink()

            driver.find_element(By.ID, "hwpxFile").send_keys(str(hwpx_path))
            wait_for(
                driver,
                "document.querySelector('#activeFileName').textContent === 'browser-sample.hwpx'",
            )
            wait_for(driver, "document.querySelector('#rhwpEditorHost') !== null")
            report["rhwpNativeEditor"] = True
            wait_for(driver, "document.querySelector('#aiSelectionMode') !== null")
            driver.find_element(By.ID, "aiSelectionMode").click()
            wait_for(driver, "document.querySelector('#targetParagraph').textContent.includes('직접 편집 원문')")
            wait_for(driver, "document.querySelector('.hwpx-table') !== null")
            merged_cell = driver.find_element(By.CSS_SELECTOR, "#documentPaper .hwpx-table td:not([colspan='1'])")
            if int(merged_cell.get_attribute("colspan")) <= 1:
                raise AssertionError("HWPX merged table cell was not preserved")
            report["hwpxTableCells"] = len(
                driver.find_elements(By.CSS_SELECTOR, "#documentPaper .hwpx-table td")
            )
            paragraph = driver.find_element(By.ID, "targetParagraph")
            if paragraph.get_attribute("contenteditable") == "true":
                raise AssertionError("imported document still uses HTML contenteditable")
            report["nativeSessionAdapter"] = "document.hwpx@1.2.0"
            second_paragraph = driver.find_elements(
                By.CSS_SELECTOR, "#documentPaper [data-native-target]"
            )[1]
            paragraph.click()
            command_text = driver.find_element(By.ID, "chatInput")
            command_text.send_keys("선택한 글귀를 보다 공손한 어투로 바꿔줘")
            driver.find_element(By.CSS_SELECTOR, "#chatForm .send-button").click()
            first_structured_proposal = approve_live_rewrite(driver)
            hwpx_edited = first_structured_proposal["after"]
            driver.find_element(By.ID, "applyProposal").click()
            wait_for(
                driver,
                "document.querySelector('#documentSaveState').textContent.includes('r2')",
            )
            wait_for(driver, "document.querySelector('#aiSelectionMode') !== null")
            driver.find_element(By.ID, "aiSelectionMode").click()
            wait_for(driver, f"document.querySelector('#targetParagraph').textContent === {json.dumps(hwpx_edited)}")
            second_paragraph = driver.find_elements(
                By.CSS_SELECTOR, "#documentPaper [data-native-target]"
            )[1]
            second_paragraph.click()
            command_text = driver.find_element(By.ID, "chatInput")
            command_text.send_keys("선택한 글귀를 보다 공손한 어투로 바꿔줘")
            driver.find_element(By.CSS_SELECTOR, "#chatForm .send-button").click()
            second_structured_proposal = approve_live_rewrite(driver)
            second_edited = second_structured_proposal["after"]
            driver.find_element(By.ID, "applyProposal").click()
            wait_for(
                driver,
                "document.querySelector('#documentSaveState').textContent.includes('r3')",
            )
            report["nativeSessionRevision"] = 3
            driver.find_element(By.ID, "saveDocument").click()
            wait_for(
                driver,
                "document.querySelector('#activeFileName').textContent.includes('_AIWorks.hwpx')",
            )
            wait_for(
                driver,
                "document.querySelector('#documentSaveState').textContent.includes('저장됨')",
            )
            report["hwpxSavedFilename"] = driver.find_element(
                By.ID, "activeFileName"
            ).get_attribute("textContent")
            driver.find_element(By.ID, "exportButton").click()
            deadline = time.time() + 10
            downloads = []
            while time.time() < deadline:
                downloads = [
                    item
                    for item in temp_dir.glob("*_AIWorks.hwpx")
                    if item.stat().st_size > 0
                ]
                if downloads:
                    break
                time.sleep(0.2)
            if not downloads:
                raise AssertionError("edited HWPX download was not created")
            with zipfile.ZipFile(native_fixture) as original:
                expected_preview = original.read("Preview/PrvImage.png")
            with zipfile.ZipFile(downloads[0]) as downloaded:
                if (
                    downloaded.read("Preview/PrvImage.png")
                    != expected_preview
                ):
                    raise AssertionError("non-target HWPX asset was not preserved")
                section = downloaded.read("Contents/section0.xml").decode()
                if hwpx_edited not in section:
                    raise AssertionError("direct HWPX edit was not present in download")
                if second_edited not in section:
                    raise AssertionError("second direct HWPX edit was not present in download")
            report["hwpxDownloadBytes"] = downloads[0].stat().st_size
            wait_for(driver, "document.querySelector('[data-document-version]') !== null")
            version_id = driver.find_element(
                By.CSS_SELECTOR, "[data-document-version]"
            ).get_attribute("data-document-version")
            version_button = driver.find_element(By.CSS_SELECTOR, "[data-document-version]")
            driver.execute_script("arguments[0].click()", version_button)
            wait_for(driver, "document.querySelector('#documentSaveState').textContent.includes('r1')")
            wait_for(driver, "document.querySelector('#aiSelectionMode') !== null")
            driver.find_element(By.ID, "aiSelectionMode").click()
            wait_for(
                driver,
                "document.querySelector('#targetParagraph') && document.querySelectorAll('#documentPaper [data-native-target]').length >= 1",
            )
            report["hwpxVersionReopened"] = version_id

            driver.find_element(By.ID, "hwpxFile").send_keys(str(markdown_path))
            wait_for(driver, "document.querySelector('#sourceEditor') !== null")
            wait_for(driver, "document.querySelector('#editorPluginRoute').textContent.includes('document.markdown')")
            driver.execute_script(
                "const e=document.querySelector('#sourceEditor'),t='검토가 필요하다.';"
                "const s=e.value.indexOf(t);e.focus();e.setSelectionRange(s,s+t.length);"
                "e.dispatchEvent(new Event('select',{bubbles:true}));"
            )
            driver.find_element(By.ID, "chatInput").send_keys("선택한 글귀를 공손하게 바꿔줘")
            driver.find_element(By.CSS_SELECTOR, "#chatForm .send-button").click()
            markdown_proposal = approve_live_rewrite(driver)
            driver.find_element(By.ID, "applyProposal").click()
            wait_for(driver, f"document.querySelector('#sourceEditor').value.includes({json.dumps(markdown_proposal['after'])})")
            report["markdownInteractiveEdit"] = True

            for view in ("builder", "data", "audit", "settings"):
                driver.find_element(
                    By.CSS_SELECTOR, f".activitybar [data-view='{view}']"
                ).click()
                wait_for(
                    driver,
                    f"document.querySelector('#{view}View').classList.contains('active')",
                )
                metrics = scroll_metrics(driver, f"#{view}View")
                report[view + "Scroll"] = metrics
                driver.execute_script(
                    "const n=document.querySelector(arguments[0]);n.scrollTop=n.scrollHeight",
                    f"#{view}View",
                )
                if metrics["scrollHeight"] > metrics["clientHeight"]:
                    position = driver.execute_script(
                        "return document.querySelector(arguments[0]).scrollTop",
                        f"#{view}View",
                    )
                    if position <= 0:
                        raise AssertionError(f"{view} scrollTop did not move")
                if view == "settings":
                    wait_for(
                        driver,
                        "document.querySelector('#rhwpRuntimeStatus').textContent.includes('설치 v1.0.0')",
                    )
                    tool_count = len(
                        driver.find_elements(By.CSS_SELECTOR, "#rhwpToolCatalog span")
                    )
                    if tool_count != 21:
                        raise AssertionError(
                            f"RHWP tool catalog count mismatch: {tool_count}"
                        )
                    report["rhwpTools"] = tool_count

            report["status"] = "passed"
            print(json.dumps(report, ensure_ascii=False, indent=2))
        finally:
            driver.quit()


if __name__ == "__main__":
    main()
